<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
* translation	2015~ minwook shin @ https://github.com/minwook-shin/phpbb-korean
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> '',
	'DIRECTION'			=> 'ltr',
	'DATE_FORMAT'		=> '|d M Y|',	// 01 Jan 2007 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|d M Y, H:i|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
	'USER_LANG'			=> 'en-gb',

	// You can define different rules for the determination of plural forms here.
	// See http://wiki.phpbb.com/Plural_Rules for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 1,

	'1_DAY'			=> '1 일',
	'1_MONTH'		=> '1 달',
	'1_YEAR'		=> '1 년',
	'2_WEEKS'		=> '2 주',
	'3_MONTHS'		=> '3 달',
	'6_MONTHS'		=> '6 달',
	'7_DAYS'		=> '7 일',

	'ACCOUNT_ALREADY_ACTIVATED'		=> '계정이 이미 활성화되었습니다.',
	'ACCOUNT_DEACTIVATED'			=> '귀하의 계정은 수동으로 비활성화 및 관리자만 활성화 할 수있습니다.',
	'ACCOUNT_NOT_ACTIVATED'			=> '귀하의 계정은 아직 활성화되지 않았습니다.',
	'ACP'							=> '관리자 제어판',
	'ACP_SHORT'						=> 'ACP',
	'ACTIVE'						=> '활성화',
	'ACTIVE_ERROR'					=> '지정된 사용자 이름은 현재 비활성 상태입니다. 계정을 활성화 문제가있는 경우, 보드 관리자에게 문의하십시오.',
	'ADMINISTRATOR'					=> '관리자',
	'ADMINISTRATORS'				=> '관리자들',
	'AGE'							=> '나이',
	'AIM'							=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'AJAX 오류',
	'AJAX_ERROR_TEXT'				=> '귀하의 요청을 처리 할 때 문제가 발생했습니다.',
	'AJAX_ERROR_TEXT_ABORT'			=> '사용자는 요청을 중단되었습니다.',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> '귀하의 요청 시간이 초과되었습니다; 다시 시도하십시오.',
	'AJAX_ERROR_TEXT_PARSERERROR'	=> '뭔가 요청에 잘못된 서버는 잘못된 응답을 반환했습니다.',
	'ALLOWED'						=> '허용됨',
	'ALL_FILES'						=> '모든 파일',
	'ALL_FORUMS'					=> '모든 포럼',
	'ALL_MESSAGES'					=> '모든 메시지',
	'ALL_POSTS'						=> '모든 글',
	'ALL_TIMES'						=> '모든 시간은 <abbr title="%2$s">%1$s</abbr>',
	'ALL_TOPICS'					=> '모든 주제',
	'AND'							=> '그리고',
	'ARE_WATCHING_FORUM'			=> '당신은 이 포럼에서 새 게시물에 대한 알림에 구독했습니다.',
	'ARE_WATCHING_TOPIC'			=> '당신은 이 주제에서 새 게시물에 대한 알림에 구독했습니다.',
	'ASCENDING'						=> '오름차순',
	'ATTACHMENTS'					=> '첨부 파일',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> '당신이 연결을 시도한 이미지 파일이 잘못되었습니다.',
	'AUTHOR'						=> '작성자',
	'AUTH_NO_PROFILE_CREATED'		=> '사용자 프로파일의 작성에 실패했습니다.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'				=> '잘못된 데이터베이스 항목.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'OAuth를 서비스 핸들러로 제공 잘못된 서비스 유형.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'OAuth 서비스가 안만들어짐',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'						=> 'Bitly',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'					=> '페이스북',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'					=> '구글',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'OAuth는 토큰 저장되지 않습니다.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'OAuth는 토큰 잘못 보관.',
	'AVATAR_DISALLOWED_CONTENT'		=> '업로드 된 파일이 공격 가능한 벡터로 확인 되었기 때문에 업로드가 거부되었습니다.',
	'AVATAR_DISALLOWED_EXTENSION'	=> '이 파일 확장자 때문에 표시 할 수없는 <strong>%s</strong>은 허용되지않음.',
	'AVATAR_EMPTY_REMOTE_DATA'		=> '원격 데이터가 잘못되었거나 손상으로 나타나기 때문에 지정된 아바타 업로드 할 수 없습니다.',
	'AVATAR_EMPTY_FILEUPLOAD'		=> '업로드 된 아바타 파일이 비어 있습니다.',
	'AVATAR_INVALID_FILENAME'		=> '%s 은 잘못된 파일이름입니다.',
	'AVATAR_NOT_UPLOADED'			=> '아바타 업로드 할 수 없습니다.',
	'AVATAR_NO_SIZE'				=> '링크 된 아바타의 너비 또는 높이를 판별 할 수 없습니다. 수동으로 입력하십시오.',
	'AVATAR_PARTIAL_UPLOAD'			=> '지정된 파일이 부분적으로 만 업로드되었습니다.',
	'AVATAR_PHP_SIZE_NA'			=> '아바타의 파일 크기가 큽니다.<br />php.ini 파일에서 허용되는 최대 파일 크기 설정 판별 할 수 없습니다.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> '아바타의 파일 크기가 큽니다. 올라가는 크기의 최대 허용은 %1$d %2$s 입니다.<br />이 php.ini 파일에 설정되어 있으며 재정의 할 수 없습니다 유의하시기 바랍니다.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> '요청이 시간 초과하기 때문에 지정된 아바타 업로드 할 수 없습니다.',
	'AVATAR_URL_INVALID'			=> '지정한 URL이 잘못되었습니다.',
	'AVATAR_URL_NOT_FOUND'			=> '지정된 파일을 찾을 수 없습니다.',
	'AVATAR_WRONG_FILESIZE'			=> '아바타의 파일 크기가 0과 %1$d %2$s 사이에 있어야합니다.',
	'AVATAR_WRONG_SIZE'				=> '제출 된 아바타는 %5$s 폭과 %6$s 높이입니다. 아바타는 %1$s 폭과 %2$s 높이 이상이여야 합니다, 하지만보다 %3$s 폭과 %4$s 높이가 크지않습니다.',

	'BACK_TO_TOP'			=> '상단',
	'BACK_TO_PREV'			=> '이전 페이지로 돌아가기',
	'BAN_TRIGGERED_BY_EMAIL'=> '이슈가 되고있는 당신의 이메일 주소를 금지했습니다.',
	'BAN_TRIGGERED_BY_IP'	=> '이슈가 되고있는 당신의 ip 주소를 금지했습니다.',
	'BAN_TRIGGERED_BY_USER'	=> '이슈가 되고있는 당신의 유저이름을 금지했습니다..',
	'BBCODE_GUIDE'			=> 'BBCode 가이드',
	'BCC'					=> 'BCC',
	'BIRTHDAYS'				=> '생일',
	'BOARD_BAN_PERM'		=> '당신은<strong>영구적으로</strong> 이 보드에서 금지됩니다.<br /><br />%2$s게시판 관리자%3$s에게 연락하여 더 자세한 정보를 얻으십시오.',
	'BOARD_BAN_REASON'		=> '금지를 한 이유: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> '<strong>%1$s</strong>까지 이 보드에서 금지 됨.<br /><br />%2$s게시판 관리자%3$s에게 연락하여 더 자세한 정보를 얻으십시오.',
	'BOARD_DISABLE'			=> '죄송하지만 이 보드는 현재 사용할 수 없습니다.',
	'BOARD_DISABLED'		=> '이 보드는 현재 사용할 수 없습니다.',
	'BOARD_UNAVAILABLE'		=> '죄송하지만 보드가 일시적으로 사용할 수 없습니다, 몇 분 후에 다시 시도하십시오.',
	'BROWSING_FORUM'		=> '유저가 이 포럼을 탐색중: %1$s',
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> '유저가 이 포럼을 탐색중: %2$s 그리고 %1$d 손님',
		2	=> '유저들이 이 포럼을 탐색중: %2$s 그리고 %1$d 손님들',
	),
	'BUTTON_EDIT'			=> '수정',
	'BUTTON_FORUM_LOCKED'	=> '잠김',
	'BUTTON_NEW_TOPIC'		=> '새로운 주제',
	'BUTTON_PM'				=> 'PM',
	'BUTTON_PM_FORWARD'		=> '앞으로',
	'BUTTON_PM_NEW'			=> '새로운 PM',
	'BUTTON_PM_REPLY'		=> '댓글 보내기',
	'BUTTON_PM_REPLY_ALL'	=> '모든 댓글',
	'BUTTON_POST_REPLY'		=> '댓글 게시',
	'BUTTON_QUOTE'			=> '인용',
	'BUTTON_TOPIC_LOCKED'	=> '잠김',
	'BYTES'					=> 'Bytes',
	'BYTES_SHORT'			=> 'B',

	'CANCEL'				=> '취소',
	'CHANGE'				=> '변경',
	'CHANGE_FONT_SIZE'		=> '폰트 크기 변경',
	'CHANGING_PREFERENCES'	=> '보드의 기본 설정 변경',
	'CHANGING_PROFILE'		=> '프로필 설정 변경',
	'CHARACTERS'			=> array(
		1	=> '%d character',
		2	=> '%d characters',
	),
	'COLLAPSE_VIEW'			=> '축소보기',
	'CLOSE_WINDOW'			=> '윈도우 닫기',
	'COLOUR_SWATCH'			=> '색상 견본',
	'COLON'					=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'				=> '확인',
	'CONFIRM_CODE'			=> '확인 코드',
	'CONFIRM_CODE_EXPLAIN'	=> '이 표시된대로 정확하게 코드를 입력합니다. 모든 문자는 대소 문자를 구별하지 않습니다.',
	'CONFIRM_CODE_WRONG'	=> '입력 확인 코드가 잘못되었습니다.',
	'CONFIRM_OPERATION'		=> '이 작업을 수행 할 필요가 있습니까?',
	'CONFIRM_AVATAR_DELETE' => '이 아바타 삭제가 확실합니까?',
	'CONGRATULATIONS'		=> '축하',
	'CONNECTION_FAILED'		=> '연결에 실패.',
	'CONNECTION_SUCCESS'	=> '연결에 성공!',
	'CONTACT'				=> '연락',
	'CONTACT_USER'			=> '%s 에게 연락하기',
	'CONTACT_US'			=> '저희에게 연락하기',
	'COOKIES_DELETED'		=> '모든 보드 쿠키가 삭제되었습니다.',
	'CURRENT_TIME'			=> '지금 시간은 %s 입니다',

	'DAY'					=> '일',
	'DAYS'					=> '일',
	'DELETE'				=> '삭제',
	'DELETE_ALL'			=> '모두 삭제',
	'DELETE_COOKIES'		=> '모든 게시판 쿠키 삭제',
	'DELETE_MARKED'			=> '마크된것 삭제',
	'DELETE_POST'			=> '글 삭제',
	'DELIMITER'				=> '구분',
	'DESCENDING'			=> '내림차순',
	'DISABLED'				=> '불가능',
	'DISPLAY'				=> '표시',
	'DISPLAY_GUESTS'		=> '게스트 표시',
	'DISPLAY_MESSAGES'		=> '이전의 메시지를 표시',
	'DISPLAY_POSTS'			=> '이전의 글 표시',
	'DISPLAY_TOPICS'		=> '이전 주제 표시',
	'DOWNLOADED'			=> '다운로드',
	'DOWNLOADING_FILE'		=> '파일 다운로드',
	'DOWNLOAD_COUNTS'		=> array(
		0	=> '아직 다운로드 되지않음',
		1	=> '%d 시간 다운로드',
		2	=> '%d 시간 다운로드',
	),

	'EDIT_POST'							=> '글 수정',
	'ELLIPSIS'							=>	'…',
	'EMAIL'								=> '이메일', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'						=> '이메일 주소',
	'EMAIL_INVALID_EMAIL'				=> '입력 한 이메일 주소가 잘못되었습니다.',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> '<strong>라인 %1$s</strong>에서 이메일을 보내는 문제로 실행. 응답: %2$s.',
	'EMPTY_SUBJECT'						=> '새로운 주제를 게시 할 때 대상을 지정해야합니다.',
	'EMPTY_MESSAGE_SUBJECT'				=> '새 메시지를 작성할 때 제목을 지정해야합니다.',
	'ENABLED'							=> '사용',
	'ENCLOSURE'							=> '둘러 쌈',
	'ENTER_USERNAME'					=> '유저 이름 입력',
	'ERR_CHANGING_DIRECTORY'			=> '디렉토리를 변경할 수 없습니다.',
	'ERR_CONNECTING_SERVER'				=> '서버에 연결 오류가 발생했습니다.',
	'ERR_JAB_AUTH'						=> 'jabber 서버에 권한을 부여 할 수 없습니다.',
	'ERR_JAB_CONNECT'					=> 'jabber 서버에 연결할 수 없습니다.',
	'ERR_UNABLE_TO_LOGIN'				=> '지정된 유저 이름 또는 암호가 올바르지 않습니다.',
	'ERR_UNWATCHING'					=> '구독을 취소하는 동안 오류가 발생했습니다..',
	'ERR_WATCHING'						=> '구독하는 동안 오류가 발생했습니다.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> '지정된 phpBB의 경로가 유효하지 않은 것으로 보입니다.',
	'ERROR'									=> '오류',
	'EXPAND_VIEW'						=> '보기 확장',
	'EXTENSION'							=> '확장',
	'EXTENSION_DISABLED'				=> '이 확장은 <strong>%s</strong> 사용할 수 없습니다..',
	'EXTENSION_DISABLED_AFTER_POSTING'	=> '이 확장은 <strong>%s</strong> 비활성화되어 더 이상 표시 할 수 없습니다.',
	'EXTENSION_DOES_NOT_EXIST'			=> '이 확장은 <strong>%s</strong> 존재하지않습니다.',

	'FACEBOOK'				=> '페이스북',
	'FAQ'					=> 'FAQ',
	'FAQ_EXPLAIN'			=> '자주 묻는 질문',
	'FILENAME'				=> '파일이름',
	'FILESIZE'				=> '파일 크기',
	'FILEDATE'				=> '파일 날짜',
	'FILE_COMMENT'			=> '파일 코멘트',
	'FILE_CONTENT_ERR'		=> '파일의 내용을 읽을 수 없습니다: %s',
	'FILE_JSON_DECODE_ERR'	=> 'JSON 파일을 디코딩 할 수 없습니다: %s',
	'FILE_NOT_FOUND'		=> '요청 된 파일을 찾을 수 없습니다: %s',
	'FIND_USERNAME'			=> '맴버 찾기',
	'FOLDER'				=> '폴더',
	'FORGOT_PASS'			=> '비밀번호를 잊어버렸습니다.',
	'FORM_INVALID'			=> '제출 형식이 잘못되었습니다. 다시 제출하십시오.',
	'FORUM'					=> '포럼',
	'FORUMS'				=> '포럼',
	'FORUMS_MARKED'			=> '포럼 읽기를 표시했습니다.',
	'FORUM_CAT'				=> '포럼 카테고리',
	'FORUM_INDEX'			=> '게시판 인덱스',
	'FORUM_LINK'			=> '포럼 링크',
	'FORUM_LOCATION'		=> '포럼 위치',
	'FORUM_LOCKED'			=> '포럼 잠김',
	'FORUM_RULES'			=> '포럼 규칙',
	'FORUM_RULES_LINK'		=> '포럼 규칙을 보려면 여기를 클릭하십시오',
	'FROM'					=> '부터',
	'FSOCK_DISABLED'		=> '<var>fsockopen</var>동작 때문에 완료 할 수 없습니다 기능을 사용 또는 조회되는 서버를 찾을 수 없습니다.',
	'FSOCK_TIMEOUT'			=> '네트워크 스트림에서 읽는 동안 시간 초과가 발생했습니다.',

	'FTP_FSOCK_HOST'				=> 'FTP 호스트',
	'FTP_FSOCK_HOST_EXPLAIN'		=> 'FTP 서버는 귀하의 사이트를 연결에 사용.',
	'FTP_FSOCK_PASSWORD'			=> 'FTP 비밀번호',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> '당신의 FTP 유저 이름를 위한 비밀번호.',
	'FTP_FSOCK_PORT'				=> 'FTP 포트',
	'FTP_FSOCK_PORT_EXPLAIN'		=> '포트는 서버에 연결하는 데 사용.',
	'FTP_FSOCK_ROOT_PATH'			=> 'phpBB의 경로',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> '당신의 phpBB를 보드에 루트에서의 경로입니다.',
	'FTP_FSOCK_TIMEOUT'				=> 'FTP 타임아웃',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> '시간은 초 단위로, 시스템은 서버로부터의 응답을 기다릴 것입니다.',
	'FTP_FSOCK_USERNAME'			=> 'FTP 유저이름',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> '사용자 이름은 서버에 연결하는 데 사용.',

	'FTP_HOST'					=> 'FTP 호스트',
	'FTP_HOST_EXPLAIN'			=> 'FTP 서버는 귀하의 사이트를 연결하는 데 사용.',
	'FTP_PASSWORD'				=> 'FTP 비밀번호',
	'FTP_PASSWORD_EXPLAIN'		=> 'FTP 사용자 이름의 암호.',
	'FTP_PORT'					=> 'FTP 포트',
	'FTP_PORT_EXPLAIN'			=> '포트는 서버에 연결하는 데 사용.',
	'FTP_ROOT_PATH'				=> 'phpBB의 경로',
	'FTP_ROOT_PATH_EXPLAIN'		=> '당신의 phpBB를 보드에 루트에서의 경로입니다.',
	'FTP_TIMEOUT'				=> 'FTP 타임아웃',
	'FTP_TIMEOUT_EXPLAIN'		=> '시간은 초 단위로, 시스템은 서버로부터의 응답을 기다릴 것입니다.',
	'FTP_USERNAME'				=> 'FTP 유저이름',
	'FTP_USERNAME_EXPLAIN'		=> '사용자 이름은 서버에 연결하는 데 사용.',

	'GENERAL_ERROR'				=> '일반 오류',
	'GB'						=> 'GB',
	'GIB'						=> 'GiB',
	'GO'						=> '가기',
	'GOOGLEPLUS'				=> '구글+',
	'GOTO_FIRST_POST'			=> '첫번째 글로 가기',
	'GOTO_LAST_POST'			=> '마지막 글로 가기',
	'GOTO_PAGE'					=> '페이지로 이동',
	'GROUP'						=> '그룹',
	'GROUPS'					=> '그룹들',
	'GROUP_ERR_TYPE'			=> '부적절한 그룹 유형을 지정.',
	'GROUP_ERR_USERNAME'		=> '어떤 그룹 이름을 지정하지 않았습니다.',
	'GROUP_ERR_USER_LONG'		=> '그룹 이름은 60자를 초과 할 수 없습니다.지정된 그룹 이름이 너무 깁니다.',
	'GUEST'						=> '손님',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> '%d 게스트 유저가 온라인입니다.',
		2	=> '%d 게스트 유저들이 온라인입니다.',
	),
	'GUEST_USERS_TOTAL'			=> array(
		1	=> '%d 손님',
		2	=> '%d 손님들',
	),
	'G_ADMINISTRATORS'			=> '어드민',
	'G_BOTS'					=> '봇',
	'G_GUESTS'					=> '손님',
	'G_REGISTERED'				=> '가입된 유저',
	'G_REGISTERED_COPPA'		=> 'COPPA 가입된 유저',
	'G_GLOBAL_MODERATORS'		=> '전체 관리자',
	'G_NEWLY_REGISTERED'		=> '새로 가입된 유저',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=> '%d 숨겨진 유저',
		2	=> '%d 숨겨진 유저들',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '%d 숨겨짐',
		2	=> '%d 숨겨짐',
	),
	'HIDE_GUESTS'					=> '손님 숨기기',
	'HIDE_ME'						=> '내 온라인 상태를 이 세션에서 숨기기',
	'HOURS'							=> '시간',
	'HOME'							=> '홈',

	'ICQ'						=> 'ICQ',
	'IF'						=> 'If',
	'IMAGE'						=> '이미지',
	'IMAGE_FILETYPE_INVALID'	=> '이미지 파일 타입인 %d 은 mimetype을 위한 %s 가 지원되지않음.',
	'IMAGE_FILETYPE_MISMATCH'	=> '이미지 파일 유형이 일치하지않음: 예상으로는 %1$s 이 확장되지만 %2$s 가 주어지며 확장됩니다.',
	'IN'						=> '안',
	'INDEX'						=> '인덱스 페이지',
	'INFORMATION'				=> '안내',
	'INSECURE_REDIRECT'			=> '잠재적으로 안전하지 않은 URL로 리디렉션하려고 노력했습니다.',
	'INTERESTS'					=> '이해',
	'INVALID_DIGEST_CHALLENGE'	=> '간추리려는 노력이 무효되었습니다.',
	'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> 아마도 잘못된 이메일 주소일것입니다?',
	'INVALID_PLURAL_RULE'		=> '선택된 복수의 규칙이 잘못되었습니다. 유효한 값은 0에서 15 사이의 정수입니다.',
	'IP'						=> 'IP',
	'IP_BLACKLISTED'			=> '당신의 ip는 %1$s 라는 블랙리스트 때문에 차단되었습니다. 자세한 내용은 참조하십시오 <a href="%2$s">%2$s</a>.',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> '참여됨',
	'JUMP_PAGE'				=> '당신이 이동하고자하는 페이지 번호를 입력합니다',
	'JUMP_TO'				=> '로 이동',
	'JUMP_TO_PAGE'			=> '페이지로 이동',
	'JUMP_TO_PAGE_CLICK'	=> '페이지로 이동합니다…',

	'KB'					=> 'KB',
	'KIB'					=> 'KiB',

	'LAST_POST'							=> '마지막 글',
	'LAST_UPDATED'						=> '마지막 업데이트됨',
	'LAST_VISIT'						=> '마지막 방문',
	'LDAP_NO_LDAP_EXTENSION'			=> 'LDAP 확장은 사용할수없음.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'LDAP 서버에 연결이 불가능합니다.',
	'LDAP_SEARCH_FAILED'				=> 'LDAP 디렉토리를 검색하는 동안 오류가 발생했습니다.',
	'LEGEND'							=> '메달',
	'LIVE_SEARCHES_NOT_ALLOWED'			=> '라이브 검색은 허용되지 않습니다.',
	'LOADING'							=> '로딩',
	'LOCATION'							=> '위치',
	'LOCK_POST'							=> '글 잠금',
	'LOCK_POST_EXPLAIN'					=> '편집 방지',
	'LOCK_TOPIC'						=> '주제 잠금',
	'LOGIN'								=> '로그인',
	'LOGIN_CHECK_PM'					=> '비공개 메시지를 확인하려면 로그인하십시오.',
	'LOGIN_CONFIRMATION'				=> '로그인 확인',
	'LOGIN_CONFIRM_EXPLAIN'				=> 'To prevent brute forcing accounts the board requires you to enter a confirmation code after a maximum amount of failed logins. The code is displayed in the image you should see below. If you are visually impaired or cannot otherwise read this code please contact the %sBoard Administrator%s.', // unused
	'LOGIN_ERROR_ATTEMPTS'				=> 'You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to solve the CAPTCHA below.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'You have not been authenticated by Apache.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'A non-existant OAuth service has been requested.',
	'LOGIN_ERROR_PASSWORD'				=> 'You have specified an incorrect password. Please check your password and try again. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'It was not possible to convert your password when updating this bulletin board’s software. Please %srequest a new password%s. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_ERROR_USERNAME'				=> 'You have specified an incorrect username. Please check your username and try again. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_FORUM'						=> 'To view or post in this forum you must enter its password.',
	'LOGIN_INFO'						=> 'In order to login you must be registered. Registering takes only a few moments but gives you increased capabilities. The board administrator may also grant additional permissions to registered users. Before you register please ensure you are familiar with our terms of use and related policies. Please ensure you read any forum rules as you navigate around the board.',
	'LOGIN_VIEWFORUM'					=> 'The board requires you to be registered and logged in to view this forum.',
	'LOGIN_EXPLAIN_EDIT'				=> 'In order to edit posts in this forum you have to be registered and logged in.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'In order to view the online list you have to be registered and logged in.',
	'LOGIN_REQUIRED'					=> 'You need to login to perform this action.',
	'LOGOUT'							=> '로그아웃',
	'LOGOUT_USER'						=> '로그아웃 [ %s ]',
	'LOG_ME_IN'							=> '본인 기억',

	'MAIN'					=> '메인',
	'MARK'					=> '표시',
	'MARK_ALL'				=> '모두 표시',
	'MARK_ALL_READ'			=> '표시된것 모두 읽기',
	'MARK_FORUMS_READ'		=> '표시된 포럼 읽기',
	'MARK_READ'				=> '표시한것읽기',
	'MARK_SUBFORUMS_READ'	=> '표시된 하위포럼 읽기',
	'MB'					=> 'MB',
	'MIB'					=> 'MiB',
	'MCP'					=> '관리자 컨트롤 패널',
	'MCP_SHORT'				=> 'MCP',
	'MEMBERLIST'			=> '맴버들',
	'MEMBERLIST_EXPLAIN'	=> '회원의 전체 목록보기',
	'MERGE'					=> '병합',
	'MERGE_POSTS'			=> '글 이동',
	'MERGE_TOPIC'			=> '주제 병합',
	'MESSAGE'				=> '메시지',
	'MESSAGES'				=> '메시지',
	'MESSAGES_COUNT'		=> array(
		1	=> '%d 메시지',
		2	=> '%d 메시지들',
	),
	'MESSAGE_BODY'			=> '메시지 본문',
	'MINUTES'				=> '분',
	'MODERATE'				=> '관리',
	'MODERATOR'				=> '관리자',
	'MODERATORS'			=> '관리자들',
	'MODULE_NOT_ACCESS'		=> '모듈에 액세스 할 수 없습니다',
	'MODULE_NOT_FIND'		=> '모듈을 찾을 수 없습니다 %s',
	'MODULE_FILE_INCORRECT_CLASS'	=> '모듈 파일이 %s 올바른 클래스를 포함하지 않습니다 [%s]',
	'MONTH'					=> '달',
	'MOVE'					=> '이동',

	'NA'						=> 'N/A',
	'NEWEST_USER'				=> 'Our newest member <strong>%s</strong>',
	'NEW_MESSAGE'				=> '새로운 메시지',
	'NEW_MESSAGES'				=> '새로운 메시지들',
	'NEW_POST'					=> '새로운 글',	// Not used anymore
	'NEW_POSTS'					=> '새로운 글들',	// Not used anymore
	'NEXT'						=> '다음',		// Used in pagination
	'NEXT_STEP'					=> '다음',
	'NEVER'						=> '절대',
	'NO'						=> '아니오',
	'NO_NOTIFICATIONS'			=> '알림이 없습니다',
	'NOT_ALLOWED_MANAGE_GROUP'	=> '당신은 이 그룹을 관리 할 수 없습니다.',
	'NOT_AUTHORISED'			=> '당신은 이 지역에 액세스 할 수있는 권한이 없습니다.',
	'NOT_WATCHING_FORUM'		=> '더 이상이 포럼에 대한 업데이트에 구독되지 않습니다.',
	'NOT_WATCHING_TOPIC'		=> '더 이상이 주제에 구독되지 않습니다.',
	'NOTIFICATIONS'				=> '알림',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '<strong>Reply</strong> from %1$s in bookmarked topic:',
	),
	'NOTIFICATION_FORUM'				=> '<em>포럼:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '<strong>Group request</strong> from %1$s to join the group %2$s.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> '<strong>Group request approved</strong> to join the group %1$s.',
	'NOTIFICATION_PM'					=> '<strong>Private Message</strong> from %1$s:',
	'NOTIFICATION_POST'					=> array(
		1	=> '<strong>Reply</strong> from %1$s in topic:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>Post approved</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>Post disapproved</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '<strong>Post approval</strong> request by %1$s:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '<strong>Quoted</strong> by %1$s in:',
	),
	'NOTIFICATION_REFERENCE'			=> '"%1$s"',
	'NOTIFICATION_REASON'				=> '<em>Reason:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'			=> '<strong>Private Message reported</strong> by %1$s:',
	'NOTIFICATION_REPORT_POST'			=> '<strong>Post reported</strong> by %1$s:',
	'NOTIFICATION_REPORT_CLOSED'		=> '<strong>Report closed</strong> by %1$s for:',
	'NOTIFICATION_TOPIC'				=> '<strong>New topic</strong> by %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>Topic approved</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>Topic disapproved</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '<strong>Topic approval</strong> request by %1$s:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> 'The notification type "%s" is missing from the file system.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> '<strong>Activation required</strong> for newly registered user: “%1$s”',
	// Used in conjuction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> 'others',
	'NOTIFICATION_X_OTHERS'				=> array(
		2	=> '%d others',
	),
	'NOTIFY_ADMIN'				=> 'Please notify the board administrator or webmaster.',
	'NOTIFY_ADMIN_EMAIL'		=> 'Please notify the board administrator or webmaster: <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> 'You are not allowed to access this file.',
	'NO_ACTION'					=> 'No action specified.',
	'NO_ADMINISTRATORS'			=> 'There are no administrators.',
	'NO_AUTH_ADMIN'				=> 'Access to the Administration Control Panel is not allowed as you do not have administrative permissions.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'You are not able to re-authenticate as a different user.',
	'NO_AUTH_OPERATION'			=> 'You do not have the necessary permissions to complete this operation.',
	'NO_AVATARS'				=> 'No avatars currently available',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'Could not connect to smtp host : %1$s : %2$s',
	'NO_BIRTHDAYS'				=> 'No birthdays today',
	'NO_EMAIL_MESSAGE'			=> 'Email message was blank.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'Could not get mail server response codes.',
	'NO_EMAIL_SUBJECT'			=> 'No email subject specified.',
	'NO_FORUM'					=> 'The forum you selected does not exist.',
	'NO_FORUMS'					=> 'This board has no forums.',
	'NO_GROUP'					=> 'The requested usergroup does not exist.',
	'NO_GROUP_MEMBERS'			=> 'This group currently has no members.',
	'NO_IPS_DEFINED'			=> 'No IP addresses or hostnames defined',
	'NO_MEMBERS'				=> 'No members found for this search criterion.',
	'NO_MESSAGES'				=> 'No messages',
	'NO_MODE'					=> 'No mode specified.',
	'NO_MODERATORS'				=> 'There are no moderators.',
	'NO_NEW_MESSAGES'			=> 'No new messages',
	'NO_NEW_POSTS'				=> 'No new posts',	// Not used anymore
	'NO_ONLINE_USERS'			=> 'No registered users',
	'NO_POSTS'					=> 'No posts',
	'NO_POSTS_TIME_FRAME'		=> 'No posts exist inside this topic for the selected time frame.',
	'NO_FEED_ENABLED'			=> 'Feeds are not available on this board.',
	'NO_FEED'					=> 'The requested feed is not available.',
	'NO_STYLE_DATA'				=> 'Could not get style data',
	'NO_SUBJECT'				=> 'No subject specified',								// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> 'The specified search backend doesn’t exist.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'No supported authentication methods.',
	'NO_TOPIC'					=> 'The requested topic does not exist.',
	'NO_TOPIC_FORUM'			=> 'The topic or forum no longer exists.',
	'NO_TOPICS'					=> 'There are no topics or posts in this forum.',
	'NO_TOPICS_TIME_FRAME'		=> 'No topics exist inside this forum for the selected time frame.',
	'NO_UNREAD_POSTS'			=> 'No unread posts',
	'NO_UPLOAD_FORM_FOUND'		=> 'Upload initiated but no valid file upload form found.',
	'NO_USER'					=> 'The requested user does not exist.',
	'NO_USERS'					=> 'The requested users do not exist.',
	'NO_USER_SPECIFIED'			=> 'No username was specified.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d attachment',
		2	=> '%d attachments',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'No posts in queue',		// 0
		1			=> '1 post in queue',		// 1
		2			=> '%d posts in queue',		// 2+
	),

	'OCCUPATION'				=> 'Occupation',
	'OFFLINE'					=> 'Offline',
	'ONLINE'					=> 'Online',
	'ONLINE_BUDDIES'			=> 'Online friends',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> 'In total there is <strong>%1$d</strong> user online :: %2$s and %3$s',
		2	=> 'In total there are <strong>%1$d</strong> users online :: %2$s and %3$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> 'In total there is <strong>%1$d</strong> user online :: %2$s, %3$s and %4$s',
		2	=> 'In total there are <strong>%1$d</strong> users online :: %2$s, %3$s and %4$s',
	),
	'OPTIONS'					=> 'Options',

	'PAGE_OF'				=> 'Page <strong>%1$d</strong> of <strong>%2$d</strong>',
	'PAGE_TITLE_NUMBER'		=> 'Page %s',
	'PASSWORD'				=> 'Password',
	'PIXEL'					=> 'px',
	'PIXELS'				=> array(
		1	=> '%d pixel',
		2	=> '%d pixels',
	),
	'PLAY_QUICKTIME_FILE'	=> 'Play Quicktime file',
	'PLEASE_WAIT'			=> 'Please wait.',
	'PM'					=> 'PM',
	'PM_REPORTED'			=> 'Click to view report',
	'POSTING_MESSAGE'		=> 'Posting message in %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'Composing private message',
	'POST'					=> 'Post',
	'POST_ANNOUNCEMENT'		=> 'Announce',
	'POST_STICKY'			=> 'Sticky',
	'POSTED'				=> 'Posted',
	'POSTED_IN_FORUM'		=> 'in',
	'POSTED_ON_DATE'		=> 'on',
	'POSTS'					=> 'Posts',
	'POSTS_UNAPPROVED'		=> 'At least one post in this topic has not been approved.',
	'POSTS_UNAPPROVED_FORUM'=> 'At least one post in this forum has not been approved.',
	'POST_BY_AUTHOR'		=> 'by',
	'POST_BY_FOE'			=> '<strong>%1$s</strong>, who is currently on your ignore list, made this post.',
	'POST_DISPLAY'			=> '%1$sDisplay this post%2$s.',
	'POST_DAY'				=> '%.2f posts per day',
	'POST_DELETED_ACTION'	=> 'Deleted post:',
	'POST_DELETED'			=> 'This post has been deleted.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s.',
	'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong> deleted the post by <strong>%1$s</strong> on %3$s for the following reason: %4$s',
	'POST_DETAILS'			=> 'Post details',
	'POST_NEW_TOPIC'		=> 'Post new topic',
	'POST_PCT'				=> '%.2f%% of all posts',
	'POST_PCT_ACTIVE'		=> '%.2f%% of user’s posts',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% of your posts',
	'POST_REPLY'			=> 'Post a reply',
	'POST_REPORTED'			=> 'Click to view report',
	'POST_SUBJECT'			=> 'Post subject',
	'POST_TIME'				=> 'Post time',
	'POST_TOPIC'			=> 'Post a new topic',
	'POST_UNAPPROVED_ACTION'	=> 'Post awaiting approval:',
	'POST_UNAPPROVED'		=> 'This post has not been approved.',
	'POWERED_BY'			=> 'Powered by %s',
	'PREVIEW'				=> 'Preview',
	'PREVIOUS'				=> 'Previous',		// Used in pagination
	'PREVIOUS_STEP'			=> 'Previous',
	'PRIVACY'				=> 'Privacy policy',
	'PRIVATE_MESSAGE'		=> 'Private message',
	'PRIVATE_MESSAGES'		=> 'Private messages',
	'PRIVATE_MESSAGING'		=> 'Private messaging',
	'PROFILE'				=> 'User Control Panel',

	'QUICK_LINKS'			=> '빠른 링크',

	'RANK'						=> '랭크',
	'READING_FORUM'				=> '%s 에서보기 주제',
	'READING_GLOBAL_ANNOUNCE'	=> '전체 공지 읽기',
	'READING_LINK'				=> '다음 포럼 링크 %s',
	'READING_TOPIC'				=> '%s 에서 주제읽기',
	'READ_PROFILE'				=> '프로필',
	'REASON'					=> '이유',
	'RECORD_ONLINE_USERS'		=> '이제까지 온라인 대부분의 사용자는 <strong>%1$s</strong> 명 이고 %2$s 이였습니다.',
	'REDIRECT'					=> '리디렉션',
	'REDIRECTS'					=> '총 리디렉션',
	'REGISTER'					=> '가입',
	'REGISTERED_USERS'			=> '가입된 유저:',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'			=> array(
		1	=> '%1$d 유저가 가입하고 %2$s 온라인',
		2	=> '%1$d 유저들이 가입하고 %2$s 온라인',
	),
	'REG_USERS_TOTAL'			=> array(
		1	=> '%d 가입됨',
		2	=> '%d 가입됨',
	),
	'REMOVE'					=> '삭제',
	'REMOVE_INSTALL'			=> '삭제, 이동 또는 당신이 당신의 보드를 사용하기 전에 install 디렉토리의 이름을 변경하시기 바랍니다. 이 디렉토리가 여전히 존재하는 경우에는 관리 제어판 (ACP)만 액세스 할 수 있습니다.',
	'REPLIES'					=> '답글',
	'REPLY_WITH_QUOTE'			=> '인용과 함께 답변',
	'REPLYING_GLOBAL_ANNOUNCE'	=> '전체 공지에 댓글',
	'REPLYING_MESSAGE'			=> '메시지에 회신 %s',
	'REPORT_BY'					=> '가 신고',
	'REPORT_POST'				=> '이글을 신고하기',
	'REPORTING_POST'			=> '글 신고중',
	'RESEND_ACTIVATION'			=> '활성화 이메일을 다시 보내기',
	'RESET'						=> '리셋',
	'RESTORE_PERMISSIONS'		=> '권한 복원',
	'RETURN_INDEX'				=> '%s인덱스 페이지로 돌아가기%s',
	'RETURN_FORUM'				=> '%s마지막 방문 포럼으로 돌아 가기%s',
	'RETURN_PAGE'				=> '%s이전 페이지로 돌아 가기%s',
	'RETURN_TOPIC'				=> '%s마지막 방문 주제로 돌아 가기%s',
	'RETURN_TO'					=> '“%s”으로 돌아가기',
	'RETURN_TO_INDEX'			=> '게시판 인덱스로 돌아가기',
	'FEED'						=> '피드',
	'FEED_NEWS'					=> '뉴스',
	'FEED_TOPICS_ACTIVE'		=> '활성화 주제',
	'FEED_TOPICS_NEW'			=> '새로운 주제',
	'RULES_ATTACH_CAN'			=> '이 포럼에 첨부 파일을 게시<strong> 할 수 있습니다</strong>',
	'RULES_ATTACH_CANNOT'		=> '이 포럼에 첨부 파일을 게시<strong> 할 수 없습니다</strong>',
	'RULES_DELETE_CAN'			=> '이 포럼에서 귀하의 게시물을<strong> 삭제할 수 있습니다</strong>',
	'RULES_DELETE_CANNOT'		=> '이 포럼에서 귀하의 게시물을<strong> 삭제할 수 없습니다</strong>',
	'RULES_DOWNLOAD_CAN'		=> '이 포럼에 첨부 파일을 다운로드를<strong>할 수 있습니다</strong>',
	'RULES_DOWNLOAD_CANNOT'		=> '이 포럼에 첨부 파일을 다운로드를<strong>할 수 없습니다</strong>',
	'RULES_EDIT_CAN'			=> '이 포럼에서 귀하의 게시물을 편집을<strong>할 수 있습니다</strong>',
	'RULES_EDIT_CANNOT'			=> '이 포럼에서 귀하의 게시물을 편집을<strong>할 수 없습니다</strong>',
	'RULES_LOCK_CAN'			=> '이 포럼에서 주제를 잠금을<strong> 할 수 있습니다</strong>',
	'RULES_LOCK_CANNOT'			=> '이 포럼에서 주제를 잠금을<strong> 할 수 없습니다</strong>',
	'RULES_POST_CAN'			=> '이 포럼에서 새 주제를 게시<strong> 할 수 있습니다</strong>',
	'RULES_POST_CANNOT'			=> '이 포럼에서 새 주제를 게시<strong> 할 수 없습니다</strong>',
	'RULES_REPLY_CAN'			=> '이 포럼의 주제에 답장을 보내기를<strong> 할 수 있습니다</strong>',
	'RULES_REPLY_CANNOT'		=> '이 포럼의 주제에 답장을 보내기를<strong> 할 수 없습니다</strong>',
	'RULES_VOTE_CAN'			=> '이 포럼의 설문 조사에 투표를<strong> 할 수 있습니다.</strong>',
	'RULES_VOTE_CANNOT'			=> '이 포럼의 설문 조사에 투표를<strong> 할 수 없습니다.</strong>',

	'SEARCH'					=> '검색',
	'SEARCH_MINI'				=> '검색…',
	'SEARCH_ADV'				=> '고급 검색',
	'SEARCH_ADV_EXPLAIN'		=> '고급 검색 옵션보기',
	'SEARCH_KEYWORDS'			=> '키워드 검색',
	'SEARCHING_FORUMS'			=> '포럼 검색',
	'SEARCH_ACTIVE_TOPICS'		=> '활성화 주제',
	'SEARCH_FOR'				=> '검색',
	'SEARCH_FORUM'				=> '이 포럼 검색…',
	'SEARCH_NEW'				=> '새로운 글',
	'SEARCH_POSTS_BY'			=> '로 글 검색',
	'SEARCH_SELF'				=> '당신의 글',
	'SEARCH_TOPIC'				=> '이 주제 검색…',
	'SEARCH_UNANSWERED'			=> '답변 하지않은 글',
	'SEARCH_UNREAD'				=> '읽지않은 글',
	'SEARCH_USER_POSTS'			=> '유저의 글 검색',
	'SECONDS'					=> '초',
	'SEE_ALL'					=> '모두 보기',
	'SELECT'					=> '선택',
	'SELECT_ALL_CODE'			=> '모두 선택',
	'SELECT_DESTINATION_FORUM'	=> '대상 포럼을 선택하세요',
	'SELECT_FORUM'				=> '포럼 선택',
	'SEND_EMAIL'				=> '이메일 보내기',				// Used for submit buttons
	'SEND_EMAIL_USER'			=> '%s 에게 이메일 보내기',
	'SEND_PRIVATE_MESSAGE'		=> '비밀 메시지 보내기',
	'SETTINGS'					=> '세팅',
	'SIGNATURE'					=> '서명',
	'SKIP'						=> '컨텐츠로 가기',
	'SKYPE'						=> '스카이프',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP 서버가 인증을 지원하지 않습니다.',
	'SORRY_AUTH_READ'			=> '당신은 이 포럼을 읽을 수있는 권한이 없습니다.',
	'SORRY_AUTH_VIEW_ATTACH'	=> '당신이 첨부 파일을 다운로드 할 수있는 권한이 없습니다.',
	'SORT_BY'					=> '정렬',
	'SORT_JOINED'				=> '가입 날짜',
	'SORT_LOCATION'				=> '위치',
	'SORT_RANK'					=> '랭크',
	'SORT_POSTS'				=> '글',
	'SORT_TOPIC_TITLE'			=> '주제 타이틀',
	'SORT_USERNAME'				=> '유저이름',
	'SPLIT_TOPIC'				=> '분할 주제',
	'SQL_ERROR_OCCURRED'		=> '이 페이지를 가져 오는 동안 SQL 오류가 발생했습니다. 이 문제가 계속되면 %s게시판 관리자%s에게 문의하시기 바랍니다.',
	'STATISTICS'				=> '통계',
	'START_WATCHING_FORUM'		=> '포럼 구독',
	'START_WATCHING_TOPIC'		=> '주제 구독',
	'STOP_WATCHING_FORUM'		=> '포럼 구독해지',
	'STOP_WATCHING_TOPIC'		=> '주제 구독해지',
	'STRING_LIST_MULTI'			=> '%1$s, 그리고 %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s 그리고 %2$s',
	'SUBFORUM'					=> '하위 포럼',
	'SUBFORUMS'					=> '하위 포럼들',
	'SUBJECT'					=> '제목',
	'SUBMIT'					=> '제출',

	'TB'				=> 'TB',
	'TERMS_USE'			=> '이용 약관',
	'TEST_CONNECTION'	=> '테스트 접속',
	'THE_TEAM'			=> '팀',
	'TIB'				=> 'TiB 크기',
	'TIME'				=> '시간',
	'TIMEOUT_PROCESSING_REQ'			=> '요청 시간이 초과되었습니다.',

	'TOO_LARGE'						=> '사용자가 입력 한 값이 너무 큽니다.',
	'TOO_LARGE_MAX_RECIPIENTS'		=> '<strong>개인 메시지에 허용되는 최대 사람 수</strong>의 값은 입력 설정이 너무 큽니다.',

	'TOO_LONG'						=> '사용자가 입력한 값이 너무 깁니다.',

	'TOO_LONG_CONFIRM_CODE'			=> '입력 확인 코드가 너무 깁니다.',
	'TOO_LONG_DATEFORMAT'			=> '입력 날짜 형식이 너무 깁니다.',
	'TOO_LONG_JABBER'				=> '입력한 jabber 계정 이름이 너무 깁니다.',
	'TOO_LONG_NEW_PASSWORD'			=> '입력한 암호가 너무 깁니다.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> '사용자가 입력한 암호 확인이 너무 깁니다.',
	'TOO_LONG_USER_PASSWORD'		=> '입력한 암호가 너무 깁니다.',
	'TOO_LONG_USERNAME'				=> '입력한 유저 이름이 너무 깁니다..',
	'TOO_LONG_EMAIL'				=> '입력한 이메일 주소가 너무 깁니다.',

	'TOO_MANY_VOTE_OPTIONS'			=> '당신은 너무 많은 옵션에 대한 투표를 위해 노력했습니다.',

	'TOO_SHORT'						=> '사용자가 입력 한 값이 너무 짧습니다.',

	'TOO_SHORT_CONFIRM_CODE'		=> '입력 확인 코드가 너무 짧습니다.',
	'TOO_SHORT_DATEFORMAT'			=> '입력 날짜 형식은 너무 짧습니다.',
	'TOO_SHORT_JABBER'				=> '입력한 jabber 계정 이름이 너무 짧습니다.',
	'TOO_SHORT_NEW_PASSWORD'		=> '입력한 암호가 너무 짧습니다.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> '사용자가 입력한 암호 확인이 너무 짧습니다.',
	'TOO_SHORT_USER_PASSWORD'		=> '입력한 암호가 너무 짧습니다.',
	'TOO_SHORT_USERNAME'			=> '입력한 유저 이름이 너무 짧습니다.',
	'TOO_SHORT_EMAIL'				=> '입력한 이메일 주소가 너무 짧습니다.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> '입력한 이메일 주소 확인이 너무 짧습니다.',
	'TOO_SMALL'						=> '사용자가 입력 한 값이 너무 작습니다.',
	'TOO_SMALL_MAX_RECIPIENTS'		=> '<strong>비밀 메시지에 허용되는 최대 유저 수</strong>의 값을 입력 설정하는 것이 너무 작습니다.',

	'TOPIC'				=> '주제',
	'TOPICS'			=> '주제들',
	'TOPICS_UNAPPROVED'	=> '이 포럼에서 하나 이상의 항목이 승인되지 않았습니다.',
	'TOPIC_ICON'		=> '주제 아이콘',
	'TOPIC_LOCKED'		=> '이 주제는 잠겼습니다, 당신의 게시물을 수정하거나 추가 응답을 할 수 없습니다.',
	'TOPIC_LOCKED_SHORT'=> '주제 잠김',
	'TOPIC_MOVED'		=> '주제 이동',
	'TOPIC_REVIEW'		=> '주제 검토',
	'TOPIC_TITLE'		=> '주제 제목',
	'TOPIC_UNAPPROVED'	=> '이 주제는 승인되지 않았습니다.',
	'TOPIC_DELETED'		=> '이 주제는 제거되었습니다.',
	'TOTAL_ATTACHMENTS'	=> '첨부(s)',
	'TOTAL_LOGS'		=> array(
		1	=> '%d 로그',
		2	=> '%d 로그들',
	),
	'TOTAL_PMS'		=> array(
		1	=> '총 %d 비공개 메시지',
		2	=> '총 %d 비공개 메시지',
	),
	'TOPIC_POLL'		=> '이 항목에서는 설문 조사를 가지고있습니다.',
	'TOTAL_POSTS'		=> '글 합계',
	'TOTAL_POSTS_COUNT'	=> array(
		2	=> '글 합계 <strong>%d</strong>',
	),
	'TOPIC_REPORTED'	=> '이 주제는 신고됨',
	'TOTAL_TOPICS'		=> array(
		2	=> '주제 합계 <strong>%d</strong>',
	),
	'TOTAL_USERS'		=> array(
		2	=> '맴버 합계 <strong>%d</strong>',
	),
	'TRACKED_PHP_ERROR'	=> 'PHP 추적 오류: %s',
	'TWITTER'			=> '트위터',

	'UNABLE_GET_IMAGE_SIZE'	=> '이미지의 크기로 하는것은 불가능합니다. 유저가 입력 한 URL이 올바른지 확인하십시오.',
	'UNABLE_TO_DELIVER_FILE'=> '파일을 제공 할 수 없습니다.',
	'UNKNOWN_BROWSER'		=> '알수없는 브라우저',
	'UNMARK_ALL'			=> '모두 마킹해제',
	'UNREAD_MESSAGES'		=> '읽지않은 메시지',
	'UNREAD_POST'			=> '읽지않은 글',
	'UNREAD_POSTS'			=> '읽지않은 글들',
	'UNWATCH_FORUM_CONFIRM'		=> '이 포럼에서 구독해지 하고자하는 의지가 확실하고 있습니까?',
	'UNWATCH_FORUM_DETAILED'	=> '당신은 포럼에서 구독해지 하고자하는 의지가 확실하고 있습니까? “%s”?',
	'UNWATCH_TOPIC_CONFIRM'		=> '당신은이 항목에서 구독 하시겠습니까?',
	'UNWATCH_TOPIC_DETAILED'	=> '당신은 주제에서 구독해지 하고자하는 의지가 확실하고 있습니까 “%s”?',
	'UNWATCHED_FORUMS'			=> '당신은 더 이상 선택한 포럼에 구독되지 않습니다..',
	'UNWATCHED_TOPICS'			=> '당신은 더 이상 선택한 주제에 구독되지 않습니다.',
	'UNWATCHED_FORUMS_TOPICS'	=> '당신은 더 이상 선택 항목에 구독되지 않습니다.',
	'UPDATE'				=> '업데이트',
	'UPLOAD_IN_PROGRESS'	=> '현재 업로드가 진행중입니다.',
	'URL_REDIRECT'			=> '브라우저가 메타 리디렉션을 지원하지 않는 경우 %s여기를 클릭하여 리디렉션하십시오%s.',
	'USERGROUPS'			=> '그룹',
	'USERNAME'				=> '유저 이름',
	'USERNAMES'				=> '유저 이름들',
	'USER_AVATAR'			=> '유저 아바타',
	'USER_CANNOT_READ'		=> '이 포럼에서 게시물을 읽을 수 없습니다.',
	'USER_POSTS'			=> array(
		1	=> '%d 글',
		2	=> '%d 글들',
	),
	'USERS'					=> '유저',
	'USE_PERMISSIONS'		=> '유저의 권한을 테스트',

	'USER_NEW_PERMISSION_DISALLOWED'	=> '죄송합니다,하지만 당신은이 기능을 사용할 수 없습니다. 당신은 여기에 등록 할 수 있으며 이 기능을 사용하려면 더 많은 참여를 해야 합니다.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'					=> '봄',
	'VIEWED_COUNTS'		=> array(
		0	=> '아직 보지않음',
		1	=> '%d 시간 조회됨',
		2	=> '%d 시간 조회됨',
	),
	'VIEWING_CONTACT_ADMIN'		=> '연락 페이지 보기',
	'VIEWING_FAQ'				=> 'FAQ 보기',
	'VIEWING_MEMBERS'			=> '맴버 자세히 보기',
	'VIEWING_ONLINE'			=> '누가 온라인인지 보기',
	'VIEWING_MCP'				=> '운영자 제어판 보기',
	'VIEWING_MEMBER_PROFILE'	=> '맴버 프로필 보기',
	'VIEWING_PRIVATE_MESSAGES'	=> '비밀 메시지 보기',
	'VIEWING_REGISTER'			=> '가입 계정',
	'VIEWING_UCP'				=> '유저 컨트롤 패널 보기',
	'VIEWS'						=> '보기',
	'VIEW_BOOKMARKS'			=> '북마크 보기',
	'VIEW_FORUM_LOGS'			=> '로그 보기',
	'VIEW_LATEST_POST'			=> '마지막 글 보기',
	'VIEW_NEWEST_POST'			=> '첫 읽지않은 글보기',
	'VIEW_NOTES'				=> '유저 노트 보기',
	'VIEW_ONLINE_TIMES'			=> array(
		1	=> '지난 %d 분 이상의 활성 사용자를 기반으로',
		2	=> '지난 %d 분 이상의 활성 사용자를 기반으로',
	),
	'VIEW_TOPIC'				=> '주제 보기',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> '공지: ',
	'VIEW_TOPIC_GLOBAL'			=> '전체 공지: ',
	'VIEW_TOPIC_LOCKED'			=> '잠김: ',
	'VIEW_TOPIC_LOGS'			=> '로그 보기',
	'VIEW_TOPIC_MOVED'			=> '이동됨: ',
	'VIEW_TOPIC_POLL'			=> '설문 조사: ',
	'VIEW_TOPIC_STICKY'			=> '붙박이: ',
	'VISIT_WEBSITE'				=> '웹사이트 방문',

	'WARNINGS'			=> '경고',
	'WARN_USER'			=> '사용자에게 경고',
	'WATCH_FORUM_CONFIRM'	=> '이 포럼을 구독하겠습니까?',
	'WATCH_FORUM_DETAILED'	=> '“%s” 포럼을 구독하겠습니까?',
	'WATCH_TOPIC_CONFIRM'	=> '이 주제를 구독 하시겠습니까?',
	'WATCH_TOPIC_DETAILED'	=> '“%s” 주제를 구독하시겠습니까?',
	'WELCOME_SUBJECT'	=> '%s 포럼에 오신것을 환영합니다.',
	'WEBSITE'			=> '웹사이트',
	'WHOIS'				=> '후이즈',
	'WHO_IS_ONLINE'		=> '누군가 접속',
	'WLM'				=> 'WLM',
	'WRONG_PASSWORD'	=> '잘못된 암호를 입력했습니다.',

	'WRONG_DATA_COLOUR'			=> '입력 한 색상 값이 잘못되었습니다.',
	'WRONG_DATA_JABBER'			=> '당신이 입력 한 이름은 유효한 jabber 계정 이름이 아닙니다.',
	'WRONG_DATA_LANG'			=> '지정한 언어가 유효하지 않습니다.',
	'WRONG_DATA_POST_SD'		=> '사용자가 지정한 후 정렬 방향이 유효하지 않습니다.',
	'WRONG_DATA_POST_SK'		=> '사용자가 지정한 후 정렬 옵션은 유효하지 않습니다.',
	'WRONG_DATA_TOPIC_SD'		=> '지정한 항목의 정렬 방향이 유효하지 않습니다.',
	'WRONG_DATA_TOPIC_SK'		=> '지정한 항목 정렬 옵션이 유효하지 않습니다..',
	'WROTE'						=> '씀',

	'YAHOO'				=> '야후 메신저',
	'YOUTUBE'			=> '유튜브',
	'YEAR'				=> '년',
	'YEAR_MONTH_DAY'	=> '(YYYY-MM-DD)',
	'YES'				=> '네',
	'YOU_LAST_VISIT'	=> '마지막 방문: %s',

	'datetime'			=> array(
		'TODAY'		=> '오늘',
		'TOMORROW'	=> '내일',
		'YESTERDAY'	=> '어제',
		'AGO'		=> array(
			0		=> '분 전보다',
			1		=> '%d 분 전',
			2		=> '%d 분 전',
		),

		'Sunday'	=> '일요일',
		'Monday'	=> '월요일',
		'Tuesday'	=> '화요일',
		'Wednesday'	=> '수요일',
		'Thursday'	=> '목요일',
		'Friday'	=> '금요일',
		'Saturday'	=> '토요일',

		'Sun'		=> '일',
		'Mon'		=> '월',
		'Tue'		=> '화',
		'Wed'		=> '수',
		'Thu'		=> '목',
		'Fri'		=> '금',
		'Sat'		=> '토',

		'January'	=> '1월',
		'February'	=> '2월',
		'March'		=> '3월',
		'April'		=> '4월',
		'May'		=> '5월',
		'June'		=> '6월',
		'July'		=> '7월',
		'August'	=> '8월',
		'September' => '9월',
		'October'	=> '10월',
		'November'	=> '11월',
		'December'	=> '12월',

		'Jan'		=> '1월',
		'Feb'		=> '2월',
		'Mar'		=> '3월',
		'Apr'		=> '4월',
		'May_short'	=> '5월',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> '6월',
		'Jul'		=> '7월',
		'Aug'		=> '8월',
		'Sep'		=> '9월',
		'Oct'		=> '10월',
		'Nov'		=> '11월',
		'Dec'		=> '12월',
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'					=> 'UTC',
		'UTC_OFFSET'			=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'		=> 'UTC+9',
		'Etc/GMT-8'		=> 'UTC+8',
		'Etc/GMT-7'		=> 'UTC+7',
		'Etc/GMT-6'		=> 'UTC+6',
		'Etc/GMT-5'		=> 'UTC+5',
		'Etc/GMT-4'		=> 'UTC+4',
		'Etc/GMT-3'		=> 'UTC+3',
		'Etc/GMT-2'		=> 'UTC+2',
		'Etc/GMT-1'		=> 'UTC+1',
		'Etc/GMT+1'		=> 'UTC-1',
		'Etc/GMT+2'		=> 'UTC-2',
		'Etc/GMT+3'		=> 'UTC-3',
		'Etc/GMT+4'		=> 'UTC-4',
		'Etc/GMT+5'		=> 'UTC-5',
		'Etc/GMT+6'		=> 'UTC-6',
		'Etc/GMT+7'		=> 'UTC-7',
		'Etc/GMT+8'		=> 'UTC-8',
		'Etc/GMT+9'		=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'Africa/Abidjan'	=> 'Africa/Abidjan',
		'Africa/Accra'		=> 'Africa/Accra',
		'Africa/Addis_Ababa'	=> 'Africa/Addis Ababa',
		'Africa/Algiers'	=> 'Africa/Algiers',
		'Africa/Asmara'		=> 'Africa/Asmara',
		'Africa/Bamako'		=> 'Africa/Bamako',
		'Africa/Bangui'		=> 'Africa/Bangui',
		'Africa/Banjul'		=> 'Africa/Banjul',
		'Africa/Bissau'		=> 'Africa/Bissau',
		'Africa/Blantyre'	=> 'Africa/Blantyre',
		'Africa/Brazzaville'	=> 'Africa/Brazzaville',
		'Africa/Bujumbura'	=> 'Africa/Bujumbura',
		'Africa/Cairo'		=> 'Africa/Cairo',
		'Africa/Casablanca'	=> 'Africa/Casablanca',
		'Africa/Ceuta'		=> 'Africa/Ceuta',
		'Africa/Conakry'	=> 'Africa/Conakry',
		'Africa/Dakar'		=> 'Africa/Dakar',
		'Africa/Dar_es_Salaam'	=> 'Africa/Dar es Salaam',
		'Africa/Djibouti'	=> 'Africa/Djibouti',
		'Africa/Douala'		=> 'Africa/Douala',
		'Africa/El_Aaiun'	=> 'Africa/El Aaiun',
		'Africa/Freetown'	=> 'Africa/Freetown',
		'Africa/Gaborone'	=> 'Africa/Gaborone',
		'Africa/Harare'		=> 'Africa/Harare',
		'Africa/Johannesburg'	=> 'Africa/Johannesburg',
		'Africa/Juba'		=> 'Africa/Juba',
		'Africa/Kampala'	=> 'Africa/Kampala',
		'Africa/Khartoum'	=> 'Africa/Khartoum',
		'Africa/Kigali'		=> 'Africa/Kigali',
		'Africa/Kinshasa'	=> 'Africa/Kinshasa',
		'Africa/Lagos'		=> 'Africa/Lagos',
		'Africa/Libreville'	=> 'Africa/Libreville',
		'Africa/Lome'		=> 'Africa/Lome',
		'Africa/Luanda'		=> 'Africa/Luanda',
		'Africa/Lubumbashi'	=> 'Africa/Lubumbashi',
		'Africa/Lusaka'		=> 'Africa/Lusaka',
		'Africa/Malabo'		=> 'Africa/Malabo',
		'Africa/Maputo'		=> 'Africa/Maputo',
		'Africa/Maseru'		=> 'Africa/Maseru',
		'Africa/Mbabane'	=> 'Africa/Mbabane',
		'Africa/Mogadishu'	=> 'Africa/Mogadishu',
		'Africa/Monrovia'	=> 'Africa/Monrovia',
		'Africa/Nairobi'	=> 'Africa/Nairobi',
		'Africa/Ndjamena'	=> 'Africa/Ndjamena',
		'Africa/Niamey'		=> 'Africa/Niamey',
		'Africa/Nouakchott'	=> 'Africa/Nouakchott',
		'Africa/Ouagadougou'	=> 'Africa/Ouagadougou',
		'Africa/Porto-Novo'	=> 'Africa/Porto-Novo',
		'Africa/Sao_Tome'	=> 'Africa/Sao Tome',
		'Africa/Tripoli'	=> 'Africa/Tripoli',
		'Africa/Tunis'		=> 'Africa/Tunis',
		'Africa/Windhoek'	=> 'Africa/Windhoek',

		'America/Adak'		=> 'America/Adak',
		'America/Anchorage'	=> 'America/Anchorage',
		'America/Anguilla'	=> 'America/Anguilla',
		'America/Antigua'	=> 'America/Antigua',
		'America/Araguaina'	=> 'America/Araguaina',

		'America/Argentina/Buenos_Aires'	=> 'America/Argentina/Buenos Aires',
		'America/Argentina/Catamarca'	=> 'America/Argentina/Catamarca',
		'America/Argentina/Cordoba'		=> 'America/Argentina/Cordoba',
		'America/Argentina/Jujuy'		=> 'America/Argentina/Jujuy',
		'America/Argentina/La_Rioja'	=> 'America/Argentina/La Rioja',
		'America/Argentina/Mendoza'		=> 'America/Argentina/Mendoza',
		'America/Argentina/Rio_Gallegos'	=> 'America/Argentina/Rio Gallegos',
		'America/Argentina/Salta'		=> 'America/Argentina/Salta',
		'America/Argentina/San_Juan'	=> 'America/Argentina/San Juan',
		'America/Argentina/San_Luis'	=> 'America/Argentina/San Luis',
		'America/Argentina/Tucuman'		=> 'America/Argentina/Tucuman',
		'America/Argentina/Ushuaia'		=> 'America/Argentina/Ushuaia',

		'America/Aruba'			=> 'America/Aruba',
		'America/Asuncion'		=> 'America/Asuncion',
		'America/Atikokan'		=> 'America/Atikokan',
		'America/Bahia'			=> 'America/Bahia',
		'America/Bahia_Banderas'	=> 'America/Bahia Banderas',
		'America/Barbados'		=> 'America/Barbados',
		'America/Belem'			=> 'America/Belem',
		'America/Belize'		=> 'America/Belize',
		'America/Blanc-Sablon'	=> 'America/Blanc-Sablon',
		'America/Boa_Vista'		=> 'America/Boa Vista',
		'America/Bogota'		=> 'America/Bogota',
		'America/Boise'			=> 'America/Boise',
		'America/Cambridge_Bay'	=> 'America/Cambridge Bay',
		'America/Campo_Grande'	=> 'America/Campo Grande',
		'America/Cancun'		=> 'America/Cancun',
		'America/Caracas'		=> 'America/Caracas',
		'America/Cayenne'		=> 'America/Cayenne',
		'America/Cayman'		=> 'America/Cayman',
		'America/Chicago'		=> 'America/Chicago',
		'America/Chihuahua'		=> 'America/Chihuahua',
		'America/Costa_Rica'	=> 'America/Costa Rica',
		'America/Creston'		=> 'America/Creston',
		'America/Cuiaba'		=> 'America/Cuiaba',
		'America/Curacao'		=> 'America/Curacao',
		'America/Danmarkshavn'	=> 'America/Danmarkshavn',
		'America/Dawson'		=> 'America/Dawson',
		'America/Dawson_Creek'	=> 'America/Dawson Creek',
		'America/Denver'		=> 'America/Denver',
		'America/Detroit'		=> 'America/Detroit',
		'America/Dominica'		=> 'America/Dominica',
		'America/Edmonton'		=> 'America/Edmonton',
		'America/Eirunepe'		=> 'America/Eirunepe',
		'America/El_Salvador'	=> 'America/El Salvador',
		'America/Fortaleza'		=> 'America/Fortaleza',
		'America/Glace_Bay'		=> 'America/Glace Bay',
		'America/Godthab'		=> 'America/Godthab',
		'America/Goose_Bay'		=> 'America/Goose Bay',
		'America/Grand_Turk'	=> 'America/Grand Turk',
		'America/Grenada'		=> 'America/Grenada',
		'America/Guadeloupe'	=> 'America/Guadeloupe',
		'America/Guatemala'		=> 'America/Guatemala',
		'America/Guayaquil'		=> 'America/Guayaquil',
		'America/Guyana'		=> 'America/Guyana',
		'America/Halifax'		=> 'America/Halifax',
		'America/Havana'		=> 'America/Havana',
		'America/Hermosillo'		=> 'America/Hermosillo',
		'America/Indiana/Indianapolis'	=> 'America/Indiana/Indianapolis',
		'America/Indiana/Knox'		=> 'America/Indiana/Knox',
		'America/Indiana/Marengo'	=> 'America/Indiana/Marengo',
		'America/Indiana/Petersburg'	=> 'America/Indiana/Petersburg',
		'America/Indiana/Tell_City'	=> 'America/Indiana/Tell City',
		'America/Indiana/Vevay'		=> 'America/Indiana/Vevay',
		'America/Indiana/Vincennes'	=> 'America/Indiana/Vincennes',
		'America/Indiana/Winamac'	=> 'America/Indiana/Winamac',
		'America/Inuvik'		=> 'America/Inuvik',
		'America/Iqaluit'		=> 'America/Iqaluit',
		'America/Jamaica'		=> 'America/Jamaica',
		'America/Juneau'		=> 'America/Juneau',
		'America/Kentucky/Louisville'	=> 'America/Kentucky/Louisville',
		'America/Kentucky/Monticello'	=> 'America/Kentucky/Monticello',
		'America/Kralendijk'	=> 'America/Kralendijk',
		'America/La_Paz'		=> 'America/La Paz',
		'America/Lima'			=> 'America/Lima',
		'America/Los_Angeles'	=> 'America/Los Angeles',
		'America/Lower_Princes'	=> 'America/Lower Princes',
		'America/Maceio'		=> 'America/Maceio',
		'America/Managua'		=> 'America/Managua',
		'America/Manaus'		=> 'America/Manaus',
		'America/Marigot'		=> 'America/Marigot',
		'America/Martinique'	=> 'America/Martinique',
		'America/Matamoros'		=> 'America/Matamoros',
		'America/Mazatlan'		=> 'America/Mazatlan',
		'America/Menominee'		=> 'America/Menominee',
		'America/Merida'		=> 'America/Merida',
		'America/Metlakatla'	=> 'America/Metlakatla',
		'America/Mexico_City'	=> 'America/Mexico City',
		'America/Miquelon'		=> 'America/Miquelon',
		'America/Moncton'		=> 'America/Moncton',
		'America/Monterrey'		=> 'America/Monterrey',
		'America/Montevideo'	=> 'America/Montevideo',
		'America/Montreal'		=> 'America/Montreal',
		'America/Montserrat'	=> 'America/Montserrat',
		'America/Nassau'		=> 'America/Nassau',
		'America/New_York'		=> 'America/New York',
		'America/Nipigon'		=> 'America/Nipigon',
		'America/Nome'			=> 'America/Nome',
		'America/Noronha'		=> 'America/Noronha',
		'America/North_Dakota/Beulah'		=> 'America/North Dakota/Beulah',
		'America/North_Dakota/Center'		=> 'America/North Dakota/Center',
		'America/North_Dakota/New_Salem'	=> 'America/North Dakota/New Salem',
		'America/Ojinaga'		=> 'America/Ojinaga',
		'America/Panama'		=> 'America/Panama',
		'America/Pangnirtung'	=> 'America/Pangnirtung',
		'America/Paramaribo'	=> 'America/Paramaribo',
		'America/Phoenix'		=> 'America/Phoenix',
		'America/Port-au-Prince'	=> 'America/Port-au-Prince',
		'America/Port_of_Spain'	=> 'America/Port of Spain',
		'America/Porto_Velho'	=> 'America/Porto Velho',
		'America/Puerto_Rico'	=> 'America/Puerto Rico',
		'America/Rainy_River'	=> 'America/Rainy River',
		'America/Rankin_Inlet'	=> 'America/Rankin Inlet',
		'America/Recife'		=> 'America/Recife',
		'America/Regina'		=> 'America/Regina',
		'America/Resolute'		=> 'America/Resolute',
		'America/Rio_Branco'	=> 'America/Rio Branco',
		'America/Santa_Isabel'	=> 'America/Santa Isabel',
		'America/Santarem'		=> 'America/Santarem',
		'America/Santiago'		=> 'America/Santiago',
		'America/Santo_Domingo'	=> 'America/Santo Domingo',
		'America/Sao_Paulo'		=> 'America/Sao Paulo',
		'America/Scoresbysund'	=> 'America/Scoresbysund',
		'America/Shiprock'		=> 'America/Shiprock',
		'America/Sitka'			=> 'America/Sitka',
		'America/St_Barthelemy'	=> 'America/St. Barthelemy',
		'America/St_Johns'		=> 'America/St. Johns',
		'America/St_Kitts'		=> 'America/St. Kitts',
		'America/St_Lucia'		=> 'America/St. Lucia',
		'America/St_Thomas'		=> 'America/St. Thomas',
		'America/St_Vincent'	=> 'America/St. Vincent',
		'America/Swift_Current'	=> 'America/Swift Current',
		'America/Tegucigalpa'	=> 'America/Tegucigalpa',
		'America/Thule'			=> 'America/Thule',
		'America/Thunder_Bay'	=> 'America/Thunder Bay',
		'America/Tijuana'		=> 'America/Tijuana',
		'America/Toronto'		=> 'America/Toronto',
		'America/Tortola'		=> 'America/Tortola',
		'America/Vancouver'		=> 'America/Vancouver',
		'America/Whitehorse'	=> 'America/Whitehorse',
		'America/Winnipeg'		=> 'America/Winnipeg',
		'America/Yakutat'		=> 'America/Yakutat',
		'America/Yellowknife'	=> 'America/Yellowknife',

		'Antarctica/Casey'		=> 'Antarctica/Casey',
		'Antarctica/Davis'		=> 'Antarctica/Davis',
		'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
		'Antarctica/Macquarie'	=> 'Antarctica/Macquarie',
		'Antarctica/Mawson'		=> 'Antarctica/Mawson',
		'Antarctica/McMurdo'	=> 'Antarctica/McMurdo',
		'Antarctica/Palmer'		=> 'Antarctica/Palmer',
		'Antarctica/Rothera'	=> 'Antarctica/Rothera',
		'Antarctica/South_Pole'	=> 'Antarctica/South Pole',
		'Antarctica/Syowa'		=> 'Antarctica/Syowa',
		'Antarctica/Vostok'		=> 'Antarctica/Vostok',

		'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

		'Asia/Aden'			=> 'Asia/Aden',
		'Asia/Almaty'		=> 'Asia/Almaty',
		'Asia/Amman'		=> 'Asia/Amman',
		'Asia/Anadyr'		=> 'Asia/Anadyr',
		'Asia/Aqtau'		=> 'Asia/Aqtau',
		'Asia/Aqtobe'		=> 'Asia/Aqtobe',
		'Asia/Ashgabat'		=> 'Asia/Ashgabat',
		'Asia/Baghdad'		=> 'Asia/Baghdad',
		'Asia/Bahrain'		=> 'Asia/Bahrain',
		'Asia/Baku'			=> 'Asia/Baku',
		'Asia/Bangkok'		=> 'Asia/Bangkok',
		'Asia/Beirut'		=> 'Asia/Beirut',
		'Asia/Bishkek'		=> 'Asia/Bishkek',
		'Asia/Brunei'		=> 'Asia/Brunei',
		'Asia/Choibalsan'	=> 'Asia/Choibalsan',
		'Asia/Chongqing'	=> 'Asia/Chongqing',
		'Asia/Colombo'		=> 'Asia/Colombo',
		'Asia/Damascus'		=> 'Asia/Damascus',
		'Asia/Dhaka'		=> 'Asia/Dhaka',
		'Asia/Dili'			=> 'Asia/Dili',
		'Asia/Dubai'		=> 'Asia/Dubai',
		'Asia/Dushanbe'		=> 'Asia/Dushanbe',
		'Asia/Gaza'			=> 'Asia/Gaza',
		'Asia/Harbin'		=> 'Asia/Harbin',
		'Asia/Hebron'		=> 'Asia/Hebron',
		'Asia/Ho_Chi_Minh'	=> 'Asia/Ho Chi Minh',
		'Asia/Hong_Kong'	=> 'Asia/Hong Kong',
		'Asia/Hovd'			=> 'Asia/Hovd',
		'Asia/Irkutsk'		=> 'Asia/Irkutsk',
		'Asia/Jakarta'		=> 'Asia/Jakarta',
		'Asia/Jayapura'		=> 'Asia/Jayapura',
		'Asia/Jerusalem'	=> 'Asia/Jerusalem',
		'Asia/Kabul'		=> 'Asia/Kabul',
		'Asia/Kamchatka'	=> 'Asia/Kamchatka',
		'Asia/Karachi'		=> 'Asia/Karachi',
		'Asia/Kashgar'		=> 'Asia/Kashgar',
		'Asia/Kathmandu'	=> 'Asia/Kathmandu',
		'Asia/Khandyga'		=> 'Asia/Khandyga',
		'Asia/Kolkata'		=> 'Asia/Kolkata',
		'Asia/Krasnoyarsk'	=> 'Asia/Krasnoyarsk',
		'Asia/Kuala_Lumpur'	=> 'Asia/Kuala Lumpur',
		'Asia/Kuching'		=> 'Asia/Kuching',
		'Asia/Kuwait'		=> 'Asia/Kuwait',
		'Asia/Macau'		=> 'Asia/Macau',
		'Asia/Magadan'		=> 'Asia/Magadan',
		'Asia/Makassar'		=> 'Asia/Makassar',
		'Asia/Manila'		=> 'Asia/Manila',
		'Asia/Muscat'		=> 'Asia/Muscat',
		'Asia/Nicosia'		=> 'Asia/Nicosia',
		'Asia/Novokuznetsk'	=> 'Asia/Novokuznetsk',
		'Asia/Novosibirsk'	=> 'Asia/Novosibirsk',
		'Asia/Omsk'			=> 'Asia/Omsk',
		'Asia/Oral'			=> 'Asia/Oral',
		'Asia/Phnom_Penh'	=> 'Asia/Phnom Penh',
		'Asia/Pontianak'	=> 'Asia/Pontianak',
		'Asia/Pyongyang'	=> 'Asia/Pyongyang',
		'Asia/Qatar'		=> 'Asia/Qatar',
		'Asia/Qyzylorda'	=> 'Asia/Qyzylorda',
		'Asia/Rangoon'		=> 'Asia/Rangoon',
		'Asia/Riyadh'		=> 'Asia/Riyadh',
		'Asia/Sakhalin'		=> 'Asia/Sakhalin',
		'Asia/Samarkand'	=> 'Asia/Samarkand',
		'Asia/Seoul'		=> '아시아/서울',
		'Asia/Shanghai'		=> 'Asia/Shanghai',
		'Asia/Singapore'	=> 'Asia/Singapore',
		'Asia/Taipei'		=> 'Asia/Taipei',
		'Asia/Tashkent'		=> 'Asia/Tashkent',
		'Asia/Tbilisi'		=> 'Asia/Tbilisi',
		'Asia/Tehran'		=> 'Asia/Tehran',
		'Asia/Thimphu'		=> 'Asia/Thimphu',
		'Asia/Tokyo'		=> 'Asia/Tokyo',
		'Asia/Ulaanbaatar'	=> 'Asia/Ulaanbaatar',
		'Asia/Urumqi'		=> 'Asia/Urumqi',
		'Asia/Ust-Nera'		=> 'Asia/Ust-Nera',
		'Asia/Vientiane'	=> 'Asia/Vientiane',
		'Asia/Vladivostok'	=> 'Asia/Vladivostok',
		'Asia/Yakutsk'		=> 'Asia/Yakutsk',
		'Asia/Yekaterinburg'	=> 'Asia/Yekaterinburg',
		'Asia/Yerevan'		=> 'Asia/Yerevan',

		'Atlantic/Azores'		=> 'Atlantic/Azores',
		'Atlantic/Bermuda'		=> 'Atlantic/Bermuda',
		'Atlantic/Canary'		=> 'Atlantic/Canary',
		'Atlantic/Cape_Verde'	=> 'Atlantic/Cape Verde',
		'Atlantic/Faroe'		=> 'Atlantic/Faroe',
		'Atlantic/Madeira'		=> 'Atlantic/Madeira',
		'Atlantic/Reykjavik'	=> 'Atlantic/Reykjavik',
		'Atlantic/South_Georgia'	=> 'Atlantic/South Georgia',
		'Atlantic/St_Helena'	=> 'Atlantic/St. Helena',
		'Atlantic/Stanley'		=> 'Atlantic/Stanley',

		'Australia/Adelaide'	=> 'Australia/Adelaide',
		'Australia/Brisbane'	=> 'Australia/Brisbane',
		'Australia/Broken_Hill'	=> 'Australia/Broken Hill',
		'Australia/Currie'		=> 'Australia/Currie',
		'Australia/Darwin'		=> 'Australia/Darwin',
		'Australia/Eucla'		=> 'Australia/Eucla',
		'Australia/Hobart'		=> 'Australia/Hobart',
		'Australia/Lindeman'	=> 'Australia/Lindeman',
		'Australia/Lord_Howe'	=> 'Australia/Lord Howe',
		'Australia/Melbourne'	=> 'Australia/Melbourne',
		'Australia/Perth'		=> 'Australia/Perth',
		'Australia/Sydney'		=> 'Australia/Sydney',

		'Europe/Amsterdam'	=> 'Europe/Amsterdam',
		'Europe/Andorra'	=> 'Europe/Andorra',
		'Europe/Athens'		=> 'Europe/Athens',
		'Europe/Belgrade'	=> 'Europe/Belgrade',
		'Europe/Berlin'		=> 'Europe/Berlin',
		'Europe/Bratislava'	=> 'Europe/Bratislava',
		'Europe/Brussels'	=> 'Europe/Brussels',
		'Europe/Bucharest'	=> 'Europe/Bucharest',
		'Europe/Budapest'	=> 'Europe/Budapest',
		'Europe/Busingen'	=> 'Europe/Busingen',
		'Europe/Chisinau'	=> 'Europe/Chisinau',
		'Europe/Copenhagen'	=> 'Europe/Copenhagen',
		'Europe/Dublin'		=> 'Europe/Dublin',
		'Europe/Gibraltar'	=> 'Europe/Gibraltar',
		'Europe/Guernsey'	=> 'Europe/Guernsey',
		'Europe/Helsinki'	=> 'Europe/Helsinki',
		'Europe/Isle_of_Man'	=> 'Europe/Isle of Man',
		'Europe/Istanbul'	=> 'Europe/Istanbul',
		'Europe/Jersey'		=> 'Europe/Jersey',
		'Europe/Kaliningrad'	=> 'Europe/Kaliningrad',
		'Europe/Kiev'		=> 'Europe/Kiev',
		'Europe/Lisbon'		=> 'Europe/Lisbon',
		'Europe/Ljubljana'	=> 'Europe/Ljubljana',
		'Europe/London'		=> 'Europe/London',
		'Europe/Luxembourg'	=> 'Europe/Luxembourg',
		'Europe/Madrid'		=> 'Europe/Madrid',
		'Europe/Malta'		=> 'Europe/Malta',
		'Europe/Mariehamn'	=> 'Europe/Mariehamn',
		'Europe/Minsk'		=> 'Europe/Minsk',
		'Europe/Monaco'		=> 'Europe/Monaco',
		'Europe/Moscow'		=> 'Europe/Moscow',
		'Europe/Oslo'		=> 'Europe/Oslo',
		'Europe/Paris'		=> 'Europe/Paris',
		'Europe/Podgorica'	=> 'Europe/Podgorica',
		'Europe/Prague'		=> 'Europe/Prague',
		'Europe/Riga'		=> 'Europe/Riga',
		'Europe/Rome'		=> 'Europe/Rome',
		'Europe/Samara'		=> 'Europe/Samara',
		'Europe/San_Marino'	=> 'Europe/San Marino',
		'Europe/Sarajevo'	=> 'Europe/Sarajevo',
		'Europe/Simferopol'	=> 'Europe/Simferopol',
		'Europe/Skopje'		=> 'Europe/Skopje',
		'Europe/Sofia'		=> 'Europe/Sofia',
		'Europe/Stockholm'	=> 'Europe/Stockholm',
		'Europe/Tallinn'	=> 'Europe/Tallinn',
		'Europe/Tirane'		=> 'Europe/Tirane',
		'Europe/Uzhgorod'	=> 'Europe/Uzhgorod',
		'Europe/Vaduz'		=> 'Europe/Vaduz',
		'Europe/Vatican'	=> 'Europe/Vatican',
		'Europe/Vienna'		=> 'Europe/Vienna',
		'Europe/Vilnius'	=> 'Europe/Vilnius',
		'Europe/Volgograd'	=> 'Europe/Volgograd',
		'Europe/Warsaw'		=> 'Europe/Warsaw',
		'Europe/Zagreb'		=> 'Europe/Zagreb',
		'Europe/Zaporozhye'	=> 'Europe/Zaporozhye',
		'Europe/Zurich'		=> 'Europe/Zurich',

		'Indian/Antananarivo'	=> 'Indian/Antananarivo',
		'Indian/Chagos'		=> 'Indian/Chagos',
		'Indian/Christmas'	=> 'Indian/Christmas',
		'Indian/Cocos'		=> 'Indian/Cocos',
		'Indian/Comoro'		=> 'Indian/Comoro',
		'Indian/Kerguelen'	=> 'Indian/Kerguelen',
		'Indian/Mahe'		=> 'Indian/Mahe',
		'Indian/Maldives'	=> 'Indian/Maldives',
		'Indian/Mauritius'	=> 'Indian/Mauritius',
		'Indian/Mayotte'	=> 'Indian/Mayotte',
		'Indian/Reunion'	=> 'Indian/Reunion',

		'Pacific/Apia'		=> 'Pacific/Apia',
		'Pacific/Auckland'	=> 'Pacific/Auckland',
		'Pacific/Chatham'	=> 'Pacific/Chatham',
		'Pacific/Chuuk'		=> 'Pacific/Chuuk',
		'Pacific/Easter'	=> 'Pacific/Easter',
		'Pacific/Efate'		=> 'Pacific/Efate',
		'Pacific/Enderbury'	=> 'Pacific/Enderbury',
		'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
		'Pacific/Fiji'		=> 'Pacific/Fiji',
		'Pacific/Funafuti'	=> 'Pacific/Funafuti',
		'Pacific/Galapagos'	=> 'Pacific/Galapagos',
		'Pacific/Gambier'	=> 'Pacific/Gambier',
		'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
		'Pacific/Guam'		=> 'Pacific/Guam',
		'Pacific/Honolulu'	=> 'Pacific/Honolulu',
		'Pacific/Johnston'	=> 'Pacific/Johnston',
		'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
		'Pacific/Kosrae'	=> 'Pacific/Kosrae',
		'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
		'Pacific/Majuro'	=> 'Pacific/Majuro',
		'Pacific/Marquesas'	=> 'Pacific/Marquesas',
		'Pacific/Midway'	=> 'Pacific/Midway',
		'Pacific/Nauru'		=> 'Pacific/Nauru',
		'Pacific/Niue'		=> 'Pacific/Niue',
		'Pacific/Norfolk'	=> 'Pacific/Norfolk',
		'Pacific/Noumea'	=> 'Pacific/Noumea',
		'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
		'Pacific/Palau'		=> 'Pacific/Palau',
		'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
		'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
		'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
		'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
		'Pacific/Saipan'	=> 'Pacific/Saipan',
		'Pacific/Tahiti'	=> 'Pacific/Tahiti',
		'Pacific/Tarawa'	=> 'Pacific/Tarawa',
		'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
		'Pacific/Wake'		=> 'Pacific/Wake',
		'Pacific/Wallis'	=> 'Pacific/Wallis',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
		'd M Y, H:i'			=> '01 Jan 2007, 13:37',
		'd M Y H:i'				=> '01 Jan 2007 13:37',
		'M jS, \'y, H:i'		=> 'Jan 1st, \'07, 13:37',
		'D M d, Y g:i a'		=> 'Mon Jan 01, 2007 1:37 pm',
		'F jS, Y, g:i a'		=> 'January 1st, 2007, 1:37 pm',
		'|d M Y|, H:i'			=> 'Today, 13:37 / 01 Jan 2007, 13:37',
		'|F jS, Y|, g:i a'		=> 'Today, 1:37 pm / January 1st, 2007, 1:37 pm',
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'D M d, Y g:i a', // Mon Jan 01, 2007 1:37 pm

));
