<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
* translation	2015~ minwook shin @ https://github.com/minwook-shin/phpbb-korean
* Moderator Control Panel is not translated.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

$lang = array_merge($lang, array(
	'ACTION'				=> '액션',
	'ACTION_NOTE'			=> '액션/노트',
	'ADD_FEEDBACK'			=> '피드백 추가',
	'ADD_FEEDBACK_EXPLAIN'	=> '만약 보고서를 추가하려면 다음과 같은 양식을 작성하십시오. 하지만 일반 텍스트를 사용하고 HTML, BBCode는 허용되지 않습니다.',
	'ADD_WARNING'			=> '주의 추가',
	'ADD_WARNING_EXPLAIN'	=> '이 사용자에게 경고를 보내려면 다음 양식을 작성하십시오. 하지만 일반 텍스트를 사용하고 HTML, BBCode는 허용되지 않습니다.',
	'ALL_ENTRIES'			=> '모든 항목',
	'ALL_NOTES_DELETED'		=> '성공적으로 모든 사용자 메모를 제거했습니다.',
	'ALL_REPORTS'			=> '모든 신고',
	'ALREADY_REPORTED'		=> '이 게시물이 이미 신고되어 있습니다.',
	'ALREADY_REPORTED_PM'	=> '이 쪽지는 이미 신고되어 있습니다.',
	'ALREADY_WARNED'		=> '경고가 이미 이 게시물에 대해 이슈되었습니다.',
	'APPROVE'				=> '승인',
	'APPROVE_POST'			=> '승인 게시물',
	'APPROVE_POST_CONFIRM'	=> '이 게시물을 승인 하시겠습니까?',
	'APPROVE_POSTS'			=> '승인 게시물들',
	'APPROVE_POSTS_CONFIRM'	=> '당신이 선택한 게시물을 승인 하시겠습니까?',
	'APPROVE_TOPIC'			=> '승인 글타래',
	'APPROVE_TOPIC_CONFIRM'	=> '당신은 이 글타래을 승인 하시겠습니까?',
	'APPROVE_TOPICS'		=> '승인 글타래들',
	'APPROVE_TOPICS_CONFIRM'=> '당신은 선택한 글타래들을 승인 하시겠습니까?',

	'CANNOT_MOVE_SAME_FORUM'=> '당신은 이미 포럼 글타래를 이동할 수 없습니다.',
	'CANNOT_WARN_ANONYMOUS'	=> '당신은 등록되지 않은 손님를 사용자 경고에 표시 할 수 없습니다.',
	'CANNOT_WARN_SELF'		=> '당신은 자신의 경고를 표시 할 수 없습니다.',
	'CAN_LEAVE_BLANK'		=> '이 작업은 비워 둘 수 있습니다.',
	'CHANGE_POSTER'			=> '포스터 변경',
	'CLOSE_PM_REPORT'		=> '개인 메시지 보고서 닫기',
	'CLOSE_PM_REPORT_CONFIRM'	=> '정말로 선택한 개인 메시지 보고서를 딛겠습니까?',
	'CLOSE_PM_REPORTS'		=> '개인 메시지 보고서 닫기',
	'CLOSE_PM_REPORTS_CONFIRM'	=> 'Are you sure you want to close the selected PM reports?',
	'CLOSE_REPORT'			=> '보고서 닫기',
	'CLOSE_REPORT_CONFIRM'	=> '정말로 선택된 보고서를 닫겠습니까?',
	'CLOSE_REPORTS'			=> '보고서들 닫기',
	'CLOSE_REPORTS_CONFIRM'	=> 'Are you sure you want to close the selected reports?',

	'DELETE_PM_REPORT'			=> 'Delete PM report',
	'DELETE_PM_REPORT_CONFIRM'	=> 'Are you sure you want to delete the selected PM report?',
	'DELETE_PM_REPORTS'			=> 'Delete PM reports',
	'DELETE_PM_REPORTS_CONFIRM'	=> 'Are you sure you want to delete the selected PM reports?',
	'DELETE_POSTS'				=> 'Delete posts',
	'DELETE_REPORT'				=> 'Delete report',
	'DELETE_REPORT_CONFIRM'		=> 'Are you sure you want to delete the selected report?',
	'DELETE_REPORTS'			=> 'Delete reports',
	'DELETE_REPORTS_CONFIRM'	=> 'Are you sure you want to delete the selected reports?',
	'DELETE_SHADOW_TOPIC'		=> 'Delete shadow 글타래',
	'DELETE_TOPICS'				=> 'Delete selected 글타래들',
	'DISAPPROVE'				=> 'Disapprove',
	'DISAPPROVE_REASON'			=> 'Reason for disapproval',
	'DISAPPROVE_POST'			=> 'Disapprove post',
	'DISAPPROVE_POST_CONFIRM'	=> 'Are you sure you want to disapprove this post?',
	'DISAPPROVE_POSTS'			=> 'Disapprove posts',
	'DISAPPROVE_POSTS_CONFIRM'	=> 'Are you sure you want to disapprove the selected posts?',
	'DISPLAY_LOG'				=> 'Display entries from previous',
	'DISPLAY_OPTIONS'			=> 'Display options',

	'EMPTY_REPORT'					=> 'You must enter a description when selecting this reason.',
	'EMPTY_TOPICS_REMOVED_WARNING'	=> 'Please note that one or several 글타래들 have been removed from the database because they were or become empty.',

	'FEEDBACK'				=> 'Feedback',
	'FORK'					=> 'Copy',
	'FORK_TOPIC'			=> 'Copy 글타래',
	'FORK_TOPIC_CONFIRM'	=> 'Are you sure you want to copy this 글타래?',
	'FORK_TOPICS'			=> 'Copy selected 글타래들',
	'FORK_TOPICS_CONFIRM'	=> 'Are you sure you want to copy the selected 글타래들?',
	'FORUM_DESC'			=> 'Description',
	'FORUM_NAME'			=> 'Forum name',
	'FORUM_NOT_EXIST'		=> 'The forum you selected does not exist.',
	'FORUM_NOT_POSTABLE'	=> 'The forum you selected cannot be posted to.',
	'FORUM_STATUS'			=> 'Forum status',
	'FORUM_STYLE'			=> 'Forum style',

	'GLOBAL_ANNOUNCEMENT'	=> 'Global announcement',

	'IP_INFO'				=> 'IP address information',
	'IPS_POSTED_FROM'		=> 'IP addresses this user has posted from',

	'LATEST_LOGS'				=> 'Latest 5 logged actions',
	'LATEST_REPORTED'			=> 'Latest 5 reports',
	'LATEST_REPORTED_PMS'		=> 'Latest 5 PM reports',
	'LATEST_UNAPPROVED'			=> 'Latest 5 posts awaiting approval',
	'LATEST_WARNING_TIME'		=> 'Latest warning issued',
	'LATEST_WARNINGS'			=> 'Latest 5 warnings',
	'LEAVE_SHADOW'				=> 'Leave shadow 글타래 in place',
	'LIST_REPORTS'				=> array(
		1	=> '%d report',
		2	=> '%d reports',
	),
	'LOCK'						=> 'Lock',
	'LOCK_POST_POST'			=> 'Lock post',
	'LOCK_POST_POST_CONFIRM'	=> 'Are you sure you want to prevent editing this post?',
	'LOCK_POST_POSTS'			=> 'Lock selected posts',
	'LOCK_POST_POSTS_CONFIRM'	=> 'Are you sure you want to prevent editing the selected posts?',
	'LOCK_TOPIC_CONFIRM'		=> 'Are you sure you want to lock this 글타래?',
	'LOCK_TOPICS'				=> 'Lock selected 글타래들',
	'LOCK_TOPICS_CONFIRM'		=> 'Are you sure you want to lock all selected 글타래들?',
	'LOGS_CURRENT_TOPIC'		=> 'Currently viewing logs of:',
	'LOGIN_EXPLAIN_MCP'			=> 'To moderate this forum you must login.',
	'LOGVIEW_VIEWTOPIC'			=> 'View 글타래',
	'LOGVIEW_VIEWLOGS'			=> 'View 글타래 log',
	'LOGVIEW_VIEWFORUM'			=> 'View forum',
	'LOOKUP_ALL'				=> 'Look up all IPs',
	'LOOKUP_IP'					=> 'Look up IP',

	'MARKED_NOTES_DELETED'		=> 'Successfully removed all marked user notes.',

	'MCP_ADD'						=> 'Add a warning',

	'MCP_BAN'					=> 'Banning',
	'MCP_BAN_EMAILS'			=> 'Ban emails',
	'MCP_BAN_IPS'				=> 'Ban IPs',
	'MCP_BAN_USERNAMES'			=> 'Ban Usernames',

	'MCP_LOGS'						=> 'Moderator logs',
	'MCP_LOGS_FRONT'				=> 'Front page',
	'MCP_LOGS_FORUM_VIEW'			=> 'Forum logs',
	'MCP_LOGS_TOPIC_VIEW'			=> 'Topic logs',

	'MCP_MAIN'						=> 'Main',
	'MCP_MAIN_FORUM_VIEW'			=> 'View forum',
	'MCP_MAIN_FRONT'				=> 'Front page',
	'MCP_MAIN_POST_DETAILS'			=> 'Post details',
	'MCP_MAIN_TOPIC_VIEW'			=> 'View 글타래',
	'MCP_MAKE_ANNOUNCEMENT'			=> 'Modify to “Announcement”',
	'MCP_MAKE_ANNOUNCEMENT_CONFIRM'	=> 'Are you sure you want to change this 글타래 to an “Announcement”?',
	'MCP_MAKE_ANNOUNCEMENTS'		=> 'Modify to “Announcements”',
	'MCP_MAKE_ANNOUNCEMENTS_CONFIRM'=> 'Are you sure you want to change the selected 글타래들 to “Announcements”?',
	'MCP_MAKE_GLOBAL'				=> 'Modify to “Global announcement”',
	'MCP_MAKE_GLOBAL_CONFIRM'		=> 'Are you sure you want to change this 글타래 to a “Global announcement”?',
	'MCP_MAKE_GLOBALS'				=> 'Modify to “Global announcements”',
	'MCP_MAKE_GLOBALS_CONFIRM'		=> 'Are you sure you want to change the selected 글타래들 to “Global announcements”?',
	'MCP_MAKE_STICKY'				=> 'Modify to “Sticky”',
	'MCP_MAKE_STICKY_CONFIRM'		=> 'Are you sure you want to change this 글타래 to a “Sticky”?',
	'MCP_MAKE_STICKIES'				=> 'Modify to “Stickies”',
	'MCP_MAKE_STICKIES_CONFIRM'		=> 'Are you sure you want to change the selected 글타래들 to “Stickies”?',
	'MCP_MAKE_NORMAL'				=> 'Modify to “Standard Topic”',
	'MCP_MAKE_NORMAL_CONFIRM'		=> 'Are you sure you want to change this 글타래 to a “Standard Topic”?',
	'MCP_MAKE_NORMALS'				=> 'Modify to “Standard Topics”',
	'MCP_MAKE_NORMALS_CONFIRM'		=> 'Are you sure you want to change the selected 글타래들 to “Standard Topics”?',

	'MCP_NOTES'						=> 'User notes',
	'MCP_NOTES_FRONT'				=> 'Front page',
	'MCP_NOTES_USER'				=> 'User details',

	'MCP_POST_REPORTS'				=> 'Reports issued on this post',

	'MCP_PM_REPORTS'				=> 'Reported PMs',
	'MCP_PM_REPORT_DETAILS'			=> 'PM Report details',
	'MCP_PM_REPORTS_CLOSED'			=> 'Closed PM reports',
	'MCP_PM_REPORTS_CLOSED_EXPLAIN'	=> 'This is a list of all reports about private messages which have previously been resolved.',
	'MCP_PM_REPORTS_OPEN'			=> 'Open PM reports',
	'MCP_PM_REPORTS_OPEN_EXPLAIN'	=> 'This is a list of all reported private messages which are still to be handled.',

	'MCP_REPORTS'					=> 'Reported messages',
	'MCP_REPORT_DETAILS'			=> 'Report details',
	'MCP_REPORTS_CLOSED'			=> 'Closed reports',
	'MCP_REPORTS_CLOSED_EXPLAIN'	=> 'This is a list of all reports about posts which have previously been resolved.',
	'MCP_REPORTS_OPEN'				=> 'Open reports',
	'MCP_REPORTS_OPEN_EXPLAIN'		=> 'This is a list of all reported posts which are still to be handled.',

	'MCP_QUEUE'								=> 'Moderation queue',
	'MCP_QUEUE_APPROVE_DETAILS'				=> '승인 details',
	'MCP_QUEUE_UNAPPROVED_POSTS'			=> 'Posts awaiting approval',
	'MCP_QUEUE_UNAPPROVED_POSTS_EXPLAIN'	=> 'This is a list of all posts which require approving before they will be visible to users.',
	'MCP_QUEUE_UNAPPROVED_TOPICS'			=> 'Topics awaiting approval',
	'MCP_QUEUE_UNAPPROVED_TOPICS_EXPLAIN'	=> 'This is a list of all 글타래들 which require approving before they will be visible to users.',
	'MCP_QUEUE_DELETED_POSTS'				=> 'Deleted posts',
	'MCP_QUEUE_DELETED_POSTS_EXPLAIN'		=> 'This is a list of all soft deleted posts. You can restore or permanently delete the posts from this screen.',
	'MCP_QUEUE_DELETED_TOPICS'				=> 'Deleted 글타래들',
	'MCP_QUEUE_DELETED_TOPICS_EXPLAIN'		=> 'This is a list of all soft deleted 글타래들. You can restore or permanently delete the 글타래들 from this screen.',

	'MCP_VIEW_USER'			=> 'View warnings for a specific user',

	'MCP_WARN'				=> 'Warnings',
	'MCP_WARN_FRONT'		=> 'Front page',
	'MCP_WARN_LIST'			=> 'List warnings',
	'MCP_WARN_POST'			=> 'Warn for specific post',
	'MCP_WARN_USER'			=> 'Warn user',

	'MERGE_POSTS_CONFIRM'	=> 'Are you sure you want to move the selected posts?',
	'MERGE_TOPIC_EXPLAIN'	=> 'Using the form below you can move selected posts into another 글타래. The posts will be split from this 글타래 and merged into the other 글타래. These posts will not be reordered and will appear as if the users posted them to the new 글타래.<br />Please enter the destination 글타래 id or click on “Select 글타래” to search for one.',
	'MERGE_TOPIC_ID'		=> 'Destination 글타래 identification number',
	'MERGE_TOPICS'			=> 'Merge 글타래들',
	'MERGE_TOPICS_CONFIRM'	=> 'Are you sure you want to merge the selected 글타래들?',
	'MODERATE_FORUM'		=> 'Moderate forum',
	'MODERATE_TOPIC'		=> 'Moderate 글타래',
	'MODERATE_POST'			=> 'Moderate post',
	'MOD_OPTIONS'			=> 'Moderator options',
	'MORE_INFO'				=> 'Further information',
	'MOST_WARNINGS'			=> 'Users with most warnings',
	'MOVE_TOPIC_CONFIRM'	=> 'Are you sure you want to move the 글타래 into a new forum?',
	'MOVE_TOPICS'			=> 'Move selected 글타래들',
	'MOVE_TOPICS_CONFIRM'	=> 'Are you sure you want to move the selected 글타래들 into a new forum?',

	'NOTIFY_POSTER_APPROVAL'		=> 'Notify poster about approval?',
	'NOTIFY_POSTER_DISAPPROVAL'		=> 'Notify poster about disapproval?',
	'NOTIFY_USER_WARN'				=> 'Notify user about warning?',
	'NOT_MODERATOR'					=> 'You are not a moderator of this forum.',
	'NO_DESTINATION_FORUM'			=> 'Please select a forum for destination.',
	'NO_DESTINATION_FORUM_FOUND'	=> 'There is no destination forum available.',
	'NO_ENTRIES'					=> 'No log entries.',
	'NO_FEEDBACK'					=> 'No feedback exists for this user.',
	'NO_FINAL_TOPIC_SELECTED'		=> 'You have to select a destination 글타래 for merging posts.',
	'NO_MATCHES_FOUND'				=> 'No matches found.',
	'NO_POST'						=> 'You have to select a post in order to warn the user for a post.',
	'NO_POST_REPORT'				=> 'This post was not reported.',
	'NO_POST_SELECTED'				=> 'You must select at least one post to perform this action.',
	'NO_POSTS_DELETED'				=> 'There are no deleted posts.',
	'NO_POSTS_QUEUE'				=> 'There are no posts waiting for approval.',
	'NO_REASON_DISAPPROVAL'			=> 'Please give an appropriate reason for disapproval.',
	'NO_REPORT'						=> 'No report found',
	'NO_REPORTS'					=> 'No reports found',
	'NO_REPORT_SELECTED'			=> 'You must select at least one report to perform this action.',
	'NO_TOPIC_ICON'					=> 'None',
	'NO_TOPIC_SELECTED'				=> 'You must select at least one 글타래 to perform this action.',
	'NO_TOPICS_DELETED'				=> 'There are no deleted 글타래들.',
	'NO_TOPICS_QUEUE'				=> 'There are no 글타래들 waiting for approval.',

	'ONLY_TOPIC'			=> 'Only 글타래 “%s”',
	'OTHER_USERS'			=> 'Other users posting from this IP',

	'QUICKMOD_ACTION_NOT_ALLOWED' => "%s not allowed as quickmod",

	'PM_REPORT_CLOSED_SUCCESS'	=> 'The selected PM report has been closed successfully.',
	'PM_REPORT_DELETED_SUCCESS'	=> 'The selected PM report has been deleted successfully.',
	'PM_REPORTED_SUCCESS'		=> 'This private message has been successfully reported.',
	'PM_REPORTS_CLOSED_SUCCESS'	=> 'The selected PM reports have been closed successfully.',
	'PM_REPORTS_DELETED_SUCCESS'=> 'The selected PM reports have been deleted successfully.',
	'PM_REPORTS_TOTAL'			=> array(
		0	=> 'There are no PM reports to review.',
		1	=> 'In total there is <strong>1</strong> PM report to review.',
		2	=> 'In total there are <strong>%d</strong> PM reports to review.',
	),
	'PM_REPORT_DETAILS'			=> 'Private message report details',
	'POSTER'					=> 'Poster',
	'POSTS_APPROVED_SUCCESS'	=> 'The selected posts have been approved.',
	'POSTS_DELETED_SUCCESS'		=> 'The selected posts have been successfully removed from the database.',
	'POSTS_DISAPPROVED_SUCCESS'	=> 'The selected posts have been disapproved.',
	'POSTS_LOCKED_SUCCESS'		=> 'The selected posts have been locked successfully.',
	'POSTS_MERGED_SUCCESS'		=> 'The selected posts have been merged.',
	'POSTS_PER_PAGE'			=> 'Posts per page',
	'POSTS_PER_PAGE_EXPLAIN'	=> '(Set to 0 to view all posts.)',
	'POSTS_RESTORED_SUCCESS'	=> 'The selected posts have been restored successfully.',
	'POSTS_UNLOCKED_SUCCESS'	=> 'The selected posts have been unlocked successfully.',
	'POST_APPROVED_SUCCESS'		=> 'The selected post has been approved.',
	'POST_DELETED_SUCCESS'		=> 'The selected post has been successfully removed from the database.',
	'POST_DISAPPROVED_SUCCESS'	=> 'The selected post has been disapproved.',
	'POST_LOCKED_SUCCESS'		=> 'Post locked successfully.',
	'POST_NOT_EXIST'			=> 'The post you requested does not exist.',
	'POST_REPORTED_SUCCESS'		=> 'This post has been successfully reported.',
	'POST_RESTORED_SUCCESS'		=> 'This post has been restored successfully.',
	'POST_UNLOCKED_SUCCESS'		=> 'Post unlocked successfully.',

	'READ_USERNOTES'			=> 'User notes',
	'READ_WARNINGS'				=> 'User warnings',
	'REPORTER'					=> 'Reporter',
	'REPORTED'					=> 'Reported',
	'REPORTED_BY'				=> 'Reported by',
	'REPORTED_ON_DATE'			=> 'on',
	'REPORTS_CLOSED_SUCCESS'	=> 'The selected reports have been closed successfully.',
	'REPORTS_DELETED_SUCCESS'	=> 'The selected reports have been deleted successfully.',
	'REPORTS_TOTAL'				=> array(
		0	=> 'There are no reports to review.',
		1	=> 'In total there is <strong>1</strong> report to review.',
		2	=> 'In total there are <strong>%d</strong> reports to review.',
	),
	'REPORT_CLOSED'				=> 'This report has already been closed.',
	'REPORT_CLOSED_SUCCESS'		=> 'The selected report has been closed successfully.',
	'REPORT_DELETED_SUCCESS'	=> 'The selected report has been deleted successfully.',
	'REPORT_DETAILS'			=> 'Report details',
	'REPORT_MESSAGE'			=> 'Report this message',
	'REPORT_MESSAGE_EXPLAIN'	=> 'Use this form to report the selected private message. Reporting should generally be used only if the message breaks forum rules. <strong>Reporting a private message will make its contents visible to all moderators.</strong>',
	'REPORT_NOTIFY'				=> 'Notify me',
	'REPORT_NOTIFY_EXPLAIN'		=> 'Informs you when your report is dealt with.',
	'REPORT_POST_EXPLAIN'		=> 'Use this form to report the selected post to the forum moderators and board administrators. Reporting should generally be used only if the post breaks forum rules.',
	'REPORT_REASON'				=> 'Report reason',
	'REPORT_TIME'				=> 'Report time',
	'RESTORE'					=> 'Restore',
	'RESTORE_POST'				=> 'Restore post',
	'RESTORE_POST_CONFIRM'		=> 'Are you sure you want to restore this post?',
	'RESTORE_POSTS'				=> 'Restore posts',
	'RESTORE_POSTS_CONFIRM'		=> 'Are you sure you want to restore the selected posts?',
	'RESTORE_TOPIC'				=> 'Restore 글타래',
	'RESTORE_TOPIC_CONFIRM'		=> 'Are you sure you want to restore this 글타래?',
	'RESTORE_TOPICS'			=> 'Restore 글타래들',
	'RESTORE_TOPICS_CONFIRM'	=> 'Are you sure you want to restore the selected 글타래들?',
	'RESYNC'					=> 'Resync',
	'RETURN_MESSAGE'			=> '%sReturn to the message%s',
	'RETURN_NEW_FORUM'			=> '%sGo to the new forum%s',
	'RETURN_NEW_TOPIC'			=> '%sGo to the new 글타래%s',
	'RETURN_PM'					=> '%sReturn to the private message%s',
	'RETURN_POST'				=> '%sReturn to the post%s',
	'RETURN_QUEUE'				=> '%sReturn to the queue%s',
	'RETURN_REPORTS'			=> '%sReturn to the reports%s',
	'RETURN_TOPIC_SIMPLE'		=> '%sReturn to the 글타래%s',

	'SEARCH_POSTS_BY_USER'				=> 'Search posts by',
	'SELECT_ACTION'						=> 'Select desired action',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENT'	=> 'Please select the forum you wish this global announcement to be displayed.',
	'SELECT_FORUM_GLOBAL_ANNOUNCEMENTS'	=> 'One or more of the selected 글타래들 are global announcements. Please select the forum you wish these to be displayed.',
	'SELECT_MERGE'						=> 'Select for merge',
	'SELECT_TOPICS_FROM'				=> 'Select 글타래들 from',
	'SELECT_TOPIC'						=> 'Select 글타래',
	'SELECT_USER'						=> 'Select user',
	'SORT_ACTION'						=> 'Log action',
	'SORT_DATE'							=> 'Date',
	'SORT_IP'							=> 'IP address',
	'SORT_WARNINGS'						=> 'Warnings',
	'SPLIT_AFTER'						=> 'Split 글타래 from selected post onwards',
	'SPLIT_FORUM'						=> 'Forum for new 글타래',
	'SPLIT_POSTS'						=> 'Split selected posts',
	'SPLIT_SUBJECT'						=> 'New 글타래 title',
	'SPLIT_TOPIC_ALL'					=> 'Split 글타래 from selected posts',
	'SPLIT_TOPIC_ALL_CONFIRM'			=> 'Are you sure you want to split this 글타래?',
	'SPLIT_TOPIC_BEYOND'				=> 'Split 글타래 at selected post',
	'SPLIT_TOPIC_BEYOND_CONFIRM'		=> 'Are you sure you want to split this 글타래 at the selected post?',
	'SPLIT_TOPIC_EXPLAIN'				=> 'Using the form below you can split a 글타래 in two, either by selecting the posts individually or by splitting at a selected post.',

	'THIS_PM_IP'				=> 'IP for this private message',
	'THIS_POST_IP'				=> 'IP for this post',
	'TOPICS_APPROVED_SUCCESS'	=> 'The selected 글타래들 have been approved.',
	'TOPICS_DELETED_SUCCESS'	=> 'The selected 글타래들 have been successfully removed from the database.',
	'TOPICS_DISAPPROVED_SUCCESS'=> 'The selected 글타래들 have been disapproved.',
	'TOPICS_FORKED_SUCCESS'		=> 'The selected 글타래들 have been copied successfully.',
	'TOPICS_LOCKED_SUCCESS'		=> 'The selected 글타래들 have been locked.',
	'TOPICS_MOVED_SUCCESS'		=> 'The selected 글타래들 have been moved successfully.',
	'TOPICS_RESTORED_SUCCESS'	=> 'The selected 글타래들 have been restored successfully.',
	'TOPICS_RESYNC_SUCCESS'		=> 'The selected 글타래들 have been resynchronised.',
	'TOPICS_TYPE_CHANGED'		=> 'Topic types changed successfully.',
	'TOPICS_UNLOCKED_SUCCESS'	=> 'The selected 글타래들 have been unlocked.',
	'TOPIC_APPROVED_SUCCESS'	=> 'The selected 글타래 has been approved.',
	'TOPIC_DELETED_SUCCESS'		=> 'The selected 글타래 has been successfully removed from the database.',
	'TOPIC_DISAPPROVED_SUCCESS'	=> 'The selected 글타래 has been disapproved.',
	'TOPIC_FORKED_SUCCESS'		=> 'The selected 글타래 has been copied successfully.',
	'TOPIC_LOCKED_SUCCESS'		=> 'The selected 글타래 has been locked.',
	'TOPIC_MOVED_SUCCESS'		=> 'The selected 글타래 has been moved successfully.',
	'TOPIC_NOT_EXIST'			=> 'The 글타래 you selected does not exist.',
	'TOPIC_RESTORED_SUCCESS'	=> 'The selected 글타래 has been restored successfully.',
	'TOPIC_RESYNC_SUCCESS'		=> 'The selected 글타래 has been resynchronised.',
	'TOPIC_SPLIT_SUCCESS'		=> 'The selected 글타래 has been split successfully.',
	'TOPIC_TIME'				=> 'Topic time',
	'TOPIC_TYPE_CHANGED'		=> 'Topic type changed successfully.',
	'TOPIC_UNLOCKED_SUCCESS'	=> 'The selected 글타래 has been unlocked.',
	'TOTAL_WARNINGS'			=> 'Total Warnings',

	'UNAPPROVED_POSTS_TOTAL'		=> array(
		0	=> 'There are no posts waiting for approval.',
		1	=> 'In total there is <strong>1</strong> post waiting for approval.',
		2	=> 'In total there are <strong>%d</strong> posts waiting for approval.',
	),
	'UNLOCK'						=> 'Unlock',
	'UNLOCK_POST'					=> 'Unlock post',
	'UNLOCK_POST_EXPLAIN'			=> 'Allow editing',
	'UNLOCK_POST_POST'				=> 'Unlock post',
	'UNLOCK_POST_POST_CONFIRM'		=> 'Are you sure you want to allow editing this post?',
	'UNLOCK_POST_POSTS'				=> 'Unlock selected posts',
	'UNLOCK_POST_POSTS_CONFIRM'		=> 'Are you sure you want to allow editing the selected posts?',
	'UNLOCK_TOPIC'					=> 'Unlock 글타래',
	'UNLOCK_TOPIC_CONFIRM'			=> 'Are you sure you want to unlock this 글타래?',
	'UNLOCK_TOPICS'					=> 'Unlock selected 글타래들',
	'UNLOCK_TOPICS_CONFIRM'			=> 'Are you sure you want to unlock all selected 글타래들?',
	'USER_CANNOT_POST'				=> 'You cannot post in this forum.',
	'USER_CANNOT_REPORT'			=> 'You cannot report posts in this forum.',
	'USER_FEEDBACK_ADDED'			=> 'User feedback added successfully.',
	'USER_WARNING_ADDED'			=> 'User warned successfully.',

	'VIEW_DETAILS'			=> 'View details',
	'VIEW_PM'				=> 'View private message',
	'VIEW_POST'				=> 'View post',

	'WARNED_USERS'			=> 'Warned users',
	'WARNED_USERS_EXPLAIN'	=> 'This is a list of users with unexpired warnings issued to them.',
	'WARNING_PM_BODY'		=> 'The following is a warning which has been issued to you by an administrator or moderator of this site.[quote]%s[/quote]',
	'WARNING_PM_SUBJECT'	=> 'Board warning issued',
	'WARNING_POST_DEFAULT'	=> 'This is a warning regarding the following post made by you: %s .',
	'NO_WARNINGS'	=> 'No warnings exist.',

	'YOU_SELECTED_TOPIC'	=> 'You selected 글타래 number %d: %s.',

	'report_reasons'		=> array(
		'TITLE'	=> array(
			'WAREZ'		=> 'Warez',
			'SPAM'		=> 'Spam',
			'OFF_TOPIC'	=> 'Off-글타래',
			'OTHER'		=> 'Other',
		),
		'DESCRIPTION' => array(
			'WAREZ'		=> 'The message contains links to illegal or pirated software.',
			'SPAM'		=> 'The reported message has the only purpose to advertise for a website or another product.',
			'OFF_TOPIC'	=> 'The reported message is off 글타래.',
			'OTHER'		=> 'The reported message does not fit into any other category, please use the further information field.',
		),
	),
));
