<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
* translation	2015~ minwook shin @ https://github.com/minwook-shin/phpbb-korean
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

// Privacy policy and T&C
$lang = array_merge($lang, array(
	'TERMS_OF_USE_CONTENT'	=> '“%1$s” (이하 “우리” 또는 “%1$s”, “%2$s”)에 접속하려면 당신은 아래 규칙에 대해 법적으로 동의해야 합니다. 만일 아래의 모든 규칙에 동의하지 않는다면 “%1$s”에 접속하거나 이용하지 마십시오. 우리는 언제든지 이 규칙을 바꿀 수 있고, 당신에게 최대한의 정보를 알릴 것입니다. 그렇더라도 개정한 것을 스스로 신중하게 살펴보아야 합니다. 바뀐 후에 “%1$s”을 계속 이용하는 것은 업데이트 또는 수정한 이 규칙에 법적으로 동의한 것으로 간주합니다.<br />
	<br />
	당신이 본 포럼에 쓰이거나 올려지는 모든 글과 파일의 권한은 “<a href="http://www.gnu.org/licenses/gpl.html">General Public License</a>” (이하 “GPL”) 로 귀속됩니다.<br />
	<br />
	당신은 많은 이에게 혐오스럽거나 모욕적인 내용, 협박이나 명예훼손 등 현행법에 저촉되는 어떠한 글도 올리지 않는 것에 동의합니다. 여기서 현행법은 “%1$s” 포럼이 호스팅 되는 나라의 현행법과 국제법입니다. 만일 그런 글을 올린다면 당신은 즉시, 그리고 영원히 추방될 것이고 우리가 필요하다고 판단하면 당신의 인터넷 서비스 제공자에게 통보할 것입니다. 이런 작업을 위해 모든 글의 ip 주소가 기록됩니다.
	</Br>당신은 “%1$s” 포럼에게 우리가 필요하다고 판단할때 언제든지 당신의 글타래를 고치거나 옮김, 잠금, 지울 수 있는 권한이 있다는 것에 동의합니다. 당신은 회원으로서 당신이 입력한 어떤 정보라도 데이터베이스에 저장되는 것에 동의합니다. 이 정보는 당신의 동의를 받지 않은 어떤 제3자에게 드러나지 않지만, 데이터를 위태롭게 하는 어떤 해킹 시도에 대해 “%1$s”은(는) 책임지지 않습니다.
	',

	'PRIVACY_POLICY'		=> '이 정책은 “%1$s” 포럼 및 그와 관련 있는 회사 (이하 “우리” 또는 “%1$s”, “%2$s”)와 phpBB (이하 “그” 또는 “그들”, “그곳”, “phpBB software”, “www.phpbb.com”, “phpBB Group”, “phpBB Teams”)를 당신이 이용하는 동안 모은 정보 (이하 “당신의 정보”)를 사용하는 것에 대한 세부사항을 설명합니다.<br />
	<br />
	당신의 정보는 두가지 방법을 통해 모아집니다. 첫번째는 “%1$s” 포럼을 살펴보는 동안 phpBB software 가 만든 쿠키 (당신 컴퓨터의 웹 브라우저 임시파일에 저장되는 작은 text 파일)를 이용하는 것입니다. 처음 두개의 쿠키에는 phpBB software 에 의해 자동으로 정해지는 유저 식별자 (이하 “user-id”)와 익명 세션 식별자 (이하 “session-id”)가 들어있습니다. 세번째 쿠키는 당신이 “%1$s” 포럼의 글타래를 살펴볼 때 만들어지고, 당신의 경험치를 개선해 글타래를 읽었다는 것을 저장합니다.<br />
	<br />
	우리는 “%1$s” 포럼을 살펴보는 동안 phpBB software 외부의 쿠키를 만들 수도 있습니다. 하지만 이것은 phpBB software 로 만든 페이지를 커버하도록 고안된 이 도큐멘트의 범위 밖에 있습니다. 두번째 방법은 당신이 우리에게 보내주는 정보를 모으는 것입니다. 이것은 다음에 제한 없이 할 수 있습니다: 익명 유저가 올린 글 (이하 “익명 글”)과 “%1$s” 포럼에 가입한 것 (이하 “당신의 계정”), 가입한 후 로그인 해서 당신이 올린 글 (이하 “당신의 글”)<br />
	<br />
	당신의 계정은 적어도 유일하게 식별되는 이름 (이하 “당신의 아이디”)과 당신의 계정으로 로그인 하기 위한 개인 비밀번호 (이하 “당신의 비밀번호”), 유효한 e-메일 주소 (이하 “당신의 e-메일”)를 담고 있습니다. “%1$s” 포럼에 있는 당신의 계정에 대한 당신의 정보는 우리가 호스팅 하는 나라에서 적용 가능한 자료보호법률의 보호를 받습니다. 당신의 아이디와 당신의 비밀번호, 당신의 e-메일 이외에 “%1$s” 포럼 가입 때 요구되는 어떤 정보도 강제 또는 선택에 상관없이 여분입니다. 모든 경우에 있어 당신의 계정 정보를 공개하는 것을 선택할 수 있습니다. 게다가 당신은 당신의 계정 안에서 phpBB software 로부터 오는 자동으로 만들어진 e-메일의 옵트인/옵트아웃(opt-in or opt-out)을 선택할 수 있습니다.<br />
	<br />
	당신의 비밀번호는 보안을 위해 암호화 (a one-way hash) 됩니다. 어쨌든 다른 웹사이트와 같은 비밀번호를 사용하지 않기를 권합니다. 당신의 비밀번호는 “%1$s” 포럼에 있는 당신의 계정에 접근할 수 있다는 것을 뜻합니다. 그러니 그것을 조심스럽게 관리하고 “%1$s” 포럼과 관련된 이 및 phpBB, 제 3자가 당신에게 정당하게 당신의 비밀번호를 물어보면 주의를 기울이세요. 당신이 당신의 계정에 대한 당신의 비밀번호를 잊었다면 phpBB software 가 제공하는 “비밀번호 찾기” 기능을 이용하세요. 이 절차는 당신이 보내준 당신의 아이디와 당신의 e-메일을 물어본 후 phpBB software 가 당신의 계정을 되살릴 새 비밀번호를 만들게 됩니다.<br />
	',
));

// Common language entries
$lang = array_merge($lang, array(
	'ACCOUNT_ACTIVE'				=> '귀하의 계정이 활성화되었습니다. 가입 해 주셔서 감사합니다.',
	'ACCOUNT_ACTIVE_ADMIN'			=> '계정이 활성화되었습니다.',
	'ACCOUNT_ACTIVE_PROFILE'		=> '계정이 성공적으로 활성화되었습니다.',
	'ACCOUNT_ADDED'					=> '당신의 계정이 생성되어, 가입 해 주셔서 감사합니다. 이제 유저 이름과 비밀번호로 로그인 할 수 있습니다.',
	'ACCOUNT_COPPA'					=> '계정 생성하지만 승인을 받아야합니다, 자세한 내용은 이메일을 확인하시기 바랍니다.',
	'ACCOUNT_EMAIL_CHANGED'			=> '계정이 업데이트되었습니다. 그러나,이 게시판은 이메일 변경에 계정 재 활성화가 필요합니다.활성화 키는 유저가 제공 한 새 이메일 주소로 전송되었습니다. 자세한 내용은 이메일을 확인하시기 바랍니다.',
	'ACCOUNT_EMAIL_CHANGED_ADMIN'	=> '계정이 업데이트되었습니다. 그러나,이 게시판은 이메일 변경에 관리자의 계정 활성화가 필요합니다.이메일은 그들에게 발송되었습니다 귀하의 계정이 활성화되었을 때 당신에게 알려드립니다.',
	'ACCOUNT_INACTIVE'				=> '당신의 계정이 생성되었습니다. 그러나,이 게시판은 정품 인증 키를 유저가 제공 한 이메일 주소로 발송 된 계정 활성화가 필요합니다. 자세한 내용은 이메일을 확인하시기 바랍니다.',
	'ACCOUNT_INACTIVE_ADMIN'		=> '당신의 계정이 생성되었습니다. 그러나,이 게시판은 관리자 그룹에 의한 계정 활성화가 필요합니다.이메일은 그들에게 발송되었습니다 귀하의 계정이 활성화 된 때 알려드립니다.',
	'ACTIVATION_EMAIL_SENT'			=> '활성화 이메일이 이메일 주소로 전송되었습니다.',
	'ACTIVATION_EMAIL_SENT_ADMIN'	=> '활성화 이메일을 관리자 이메일 주소로 전송되었습니다.',
	'ADD'							=> '추가',
	'ADD_BCC'						=> '[BCC] 추가',
	'ADD_FOES'						=> '새 싫어하는 친구 추가',
	'ADD_FOES_EXPLAIN'				=> '당신은 다른 줄에 여러 유저 이름을 각각 입력 할 수 있습니다.',
	'ADD_FOLDER'					=> '폴더 추가',
	'ADD_FRIENDS'					=> '새로운 친구들 추가',
	'ADD_FRIENDS_EXPLAIN'			=> '당신은 다른 줄에 여러 유저 이름을 각각 입력 할 수 있습니다.',
	'ADD_NEW_RULE'					=> '새로운 규칙 추가',
	'ADD_RULE'						=> '규칙추가',
	'ADD_TO'						=> '[To] 추가',
	'ADD_USERS_UCP_EXPLAIN'			=> '여기에서 그룹에 새로운 유저를 추가 할 수 있습니다. 이 그룹은 선택한 유저에 대한 새로운 기본값이되는 여부를 선택할 수 있습니다. 별도의 줄에 각 유저 이름을 입력하세요.',
	'ADMIN_EMAIL'					=> '관리자는 나에게 정보를 이메일로 보낼 수 있습니다',
	'AGREE'							=> '이 약관에 동의합니다',
	'ALLOW_PM'						=> '유저가 당신에게 비공개 메시지를 보내도록 허용',
	'ALLOW_PM_EXPLAIN'				=> '관리자와 운영자는 항상 당신에게 메시지를 보낼 수 있습니다.',
	'ALREADY_ACTIVATED'				=> '이미 계정을 활성화 함.',
	'ATTACHMENTS_EXPLAIN'			=> '이것은 당신이 이 게시판의 게시물에서 만든 첨부 파일의 목록입니다.',
	'ATTACHMENTS_DELETED'			=> '첨부 파일이 삭제됨.',
	'ATTACHMENT_DELETED'			=> '첨부 파일이 삭제됨.',
	'AUTOLOGIN_SESSION_KEYS_DELETED'=> '"본인 기억하기"가 선택되어있는것의 로그인 키를 성공적으로 삭제했습니다.',
	'AVATAR_CATEGORY'				=> '카테고리',
	'AVATAR_DRIVER_GRAVATAR_TITLE'	=> 'Gravatar',
	'AVATAR_DRIVER_GRAVATAR_EXPLAIN'=> 'Gravatar는 당신이 여러 웹 사이트에서 동일한 아바타를 유지 할 수있는 서비스입니다. 자세한 내용은 <a href="http://www.gravatar.com/"> Gravatar </a>를 참조하십시오.',
	'AVATAR_DRIVER_LOCAL_TITLE'		=> '아바타 갤러리',
	'AVATAR_DRIVER_LOCAL_EXPLAIN'	=> '당신은 로컬의 아바타로 사용할 세트에서 자신의 아바타를 선택할 수 있습니다.',
	'AVATAR_DRIVER_REMOTE_TITLE'	=> '아바타 원격',
	'AVATAR_DRIVER_REMOTE_EXPLAIN'	=> '다른 웹사이트에서 아바타 이미지를 링크하기.',
	'AVATAR_DRIVER_UPLOAD_TITLE'	=> '아바타 업로드',
	'AVATAR_DRIVER_UPLOAD_EXPLAIN'	=> '자신 만의 아바타를 업로드합니다.',
	'AVATAR_EXPLAIN'				=> '최대 크기; 폭: %1$s, 높이: %2$s, 파일 크기: %3$.2f KiB.',
	'AVATAR_FEATURES_DISABLED'		=> '아바타 기능은 현재 사용할 수 없습니다.',
	'AVATAR_GALLERY'				=> '로컬 갤러리',
	'AVATAR_GENERAL_UPLOAD_ERROR'	=> '%s으로 아바타가 업로드되지않음.',
	'AVATAR_NOT_ALLOWED'			=> '아바타가 비허용 되었기 때문에 자신의 아바타를 표시 할 수 없습니다.',
	'AVATAR_PAGE'					=> '페이지',
	'AVATAR_SELECT'					=> '당신의 아바타 선택',
	'AVATAR_TYPE'					=> '아바타 타입',
	'AVATAR_TYPE_NOT_ALLOWED'		=> '그 유형이 비허용되어 있기 때문에 현재 아바타를 표시 할 수 없습니다.',

	'BACK_TO_DRAFTS'			=> '저장된 초안으로 돌아가기',
	'BACK_TO_LOGIN'				=> '로그인 화면으로 돌아가기',
	'BIRTHDAY'					=> '생일',
	'BIRTHDAY_EXPLAIN'			=> '그것은 당신의 생일을 설정하면 나이로 나열됩니다.',
	'BOARD_DATE_FORMAT'			=> '나의 데이타 형식',
	'BOARD_DATE_FORMAT_EXPLAIN'	=> '사용 된 구문의 PHP는 <a의 href="http://www.php.net/date"> date() </a>에 기능과 동일합니다.',
	'BOARD_LANGUAGE'			=> '나의 언어',
	'BOARD_STYLE'				=> '나의 게시판 스타일',
	'BOARD_TIMEZONE'			=> '나의 타임존',
	'BOOKMARKS'					=> '북마크',
	'BOOKMARKS_EXPLAIN'			=> '당신은 나중에 참조 할 글타래를 즐겨 찾기에 추가 할 수 있습니다. 삭제하려는 북마크의 확인란을 선택한 다음 <EM>북마크 제거</EM> 버튼을 누릅니다.',
	'BOOKMARKS_DISABLED'		=> '북마크는 이 보드에 사용할 수 없습니다.',
	'BOOKMARKS_REMOVED'			=> '북마크가 성공적으로 삭제되었습니다.',

	'CANNOT_EDIT_MESSAGE_TIME'	=> '해당 메시지를 더 이상 편집하거나 삭제할 수 없습니다.',
	'CANNOT_MOVE_TO_SAME_FOLDER'=> '메시지는 제거 할 폴더로 이동할 수 없습니다.',
	'CANNOT_MOVE_FROM_SPECIAL'	=> '메시지는 보낼 편지함에서 이동할 수 없습니다.',
	'CANNOT_RENAME_FOLDER'		=> '이 폴더는 이름을 바꿀 수 없습니다.',
	'CANNOT_REMOVE_FOLDER'		=> '이 폴더는 제거 할 수 없습니다.',
	'CHANGE_DEFAULT_GROUP'		=> '기본 그룹 변경',
	'CHANGE_PASSWORD'			=> '비밀번호 변경',
	'CLICK_GOTO_FOLDER'			=> '%1$s로 이동하여 “%3$s” 폴더%2$s',
	'CLICK_RETURN_FOLDER'		=> '%1$s로 돌아 가기 “%3$s” 폴더%2$s',
	'CONFIRMATION'				=> '가입 확인',
	'CONFIRM_CHANGES'			=> '변경 사항 확인',
	'CONFIRM_EXPLAIN'			=> '자동 등록을 방지하기 위해 게시판은 확인 코드를 입력해야합니다. 코드는 아래 이미지에 표시되는것을 참조해야합니다. 당신은 시각 장애인 또는 이 코드를 읽을 수없는 경우 %s 게시판 관리자 % s에게 문의하시기 바랍니다.',
	'VC_REFRESH'				=> '확인 코드 새로고침 ',
	'VC_REFRESH_EXPLAIN'		=> '당신이 코드를 읽을 수없는 경우에는 버튼을 클릭하여 새로운 코드를 요청할 수 있습니다.',

	'CONFIRM_PASSWORD'			=> '비밀번호 확인',
	'CONFIRM_PASSWORD_EXPLAIN'	=> '위를 변경하는 경우에만 암호를 확인해야합니다.',
	'COPPA_BIRTHDAY'			=> '당신이 태어난 때에 대한 등록 절차를 계속하려면 입력해주십시오.',
	'COPPA_COMPLIANCE'			=> 'COPPA 준수',
	'COPPA_EXPLAIN'				=> '제출을 클릭하면 계정이 생성됩니다. 부모 혹은 보호자가 등록을 승인 할 때까지는 이를 활성화 할 수 없습니다. 세부 사항의 필요한 형태의 사본이 이메일로 전송됩니다.',
	'CREATE_FOLDER'				=> '폴더 추가…',
	'CURRENT_IMAGE'				=> '현재 이미지',
	'CURRENT_PASSWORD'			=> '현재 비밀번호',
	'CURRENT_PASSWORD_EXPLAIN'	=> '당신이 이메일 주소 혹은 사용자 이름을 변경하고자 하는 경우에는 현재 암호를 입력해야합니다.',
	'CURRENT_CHANGE_PASSWORD_EXPLAIN' => '비밀번호, 이메일 주소 또는 사용자 이름을 변경하려면 현재 암호를 입력해야합니다.',
	'CUR_PASSWORD_EMPTY'		=> '당신의 현재 암호를 입력하지 않았습니다.',
	'CUR_PASSWORD_ERROR'		=> '입력 현재 암호가 올바르지 않습니다.',
	'CUSTOM_DATEFORMAT'			=> '커스텀…',

	'DEFAULT_ACTION'			=> '기본 동작',
	'DEFAULT_ACTION_EXPLAIN'	=> '위의 어느 것도 적용 할 수없는 경우 이 작업이 트리거됩니다.',
	'DEFAULT_ADD_SIG'			=> '기본적으로 내 서명을 첨부하기',
	'DEFAULT_BBCODE'			=> '기본적으로 BBCode 활성화하기',
	'DEFAULT_NOTIFY'			=> '기본적으로 댓글을 통지하기',
	'DEFAULT_SMILIES'			=> '기본적으로 이모티콘 활성화하기',
	'DEFINED_RULES'				=> '정의 된 규칙',
	'DELETED_TOPIC'				=> '글타래가 삭제됨.',
	'DELETE_ATTACHMENT'			=> '첨부파일 삭제',
	'DELETE_ATTACHMENTS'		=> '첨부파일들 삭제',
	'DELETE_ATTACHMENT_CONFIRM'	=> '이 첨부 파일을 삭제 하시겠습니까?',
	'DELETE_ATTACHMENTS_CONFIRM'=> '당신이 첨부 파일을 삭제 하시겠습니까?',
	'DELETE_AVATAR'				=> '이미지 삭제',
	'DELETE_COOKIES_CONFIRM'	=> '이 게시판을 설정 한 모든 쿠키를 삭제 하시겠습니까?',
	'DELETE_MARKED_PM'			=> '마크된 메시지 삭제',
	'DELETE_MARKED_PM_CONFIRM'	=> '당신은 모든 표시된 메시지를 삭제 하시겠습니까?',
	'DELETE_OLDEST_MESSAGES'	=> '오래된 메시지 삭제',
	'DELETE_MESSAGE'			=> '메시지 삭제',
	'DELETE_MESSAGE_CONFIRM'	=> '이 쪽지를 삭제 하시겠습니까?',
	'DELETE_MESSAGES_IN_FOLDER'	=> '삭제 된 폴더 내의 모든 메시지 삭제',
	'DELETE_RULE'				=> '규칙 삭제',
	'DELETE_RULE_CONFIRM'		=> '당신은 이 규칙을 삭제 하시겠습니까?',
	'DEMOTE_SELECTED'			=> '강등 선택',
	'DISABLE_CENSORS'			=> '단어 검열 사용',
	'DISPLAY_GALLERY'			=> '갤러리 출력',
	'DOMAIN_NO_MX_RECORD_EMAIL'	=> '입력 한 이메일 도메인은 유효한 MX 레코드가 없습니다.',
	'DOWNLOADS'					=> '다운로드',
	'DRAFTS_DELETED'			=> '선택한 모든 초안이 성공적으로 삭제되었습니다.',
	'DRAFTS_EXPLAIN'			=> '여기 저장된 초안을 보고, 편집하고 삭제할 수 있습니다.',
	'DRAFT_UPDATED'				=> '초안이 성공적으로 업데이트되었습니다.',

	'EDIT_DRAFT_EXPLAIN'		=> '여기에 당신은 당신의 초안을 편집 할 수 있습니다. 초안은 첨부 파일 및 설문 조사 정보가 포함되어 있지 않습니다.',
	'EMAIL_BANNED_EMAIL'		=> '사용자가 입력 한 이메일 주소가 사용될 수 없다.',
	'EMAIL_REMIND'				=> '이 귀하의 계정과 연결된 이메일 주소 여야합니다. 당신이 당신의 사용자 제어판을 통해이 변경되지 않은 경우, 그것은 당신이 귀하의 계정에 등록 된 이메일 주소입니다.',
	'EMAIL_TAKEN_EMAIL'			=> '입력 한 이메일 주소가 이미 사용 중입니다.',
	'EMPTY_DRAFT'				=> '당신의 변경 사항을 제출하는 메시지를 입력해야합니다.',
	'EMPTY_DRAFT_TITLE'			=> '당신은 초안 제목을 입력해야합니다.',
	'EXPORT_AS_XML'				=> 'XML로 내보내기',
	'EXPORT_AS_CSV'				=> 'CSV로 내보내기',
	'EXPORT_AS_CSV_EXCEL'		=> 'CSV (Excel)로 내보내기',
	'EXPORT_AS_TXT'				=> 'TXT로 내보내기',
	'EXPORT_AS_MSG'				=> 'MSG로 내보내기',
	'EXPORT_FOLDER'				=> 'view로 내보내기',

	'FIELD_REQUIRED'					=> '필드 "%s"를 완료해야합니다..',
	'FIELD_TOO_SHORT'					=> array(
		1	=> '필드가 "%2$s"는 너무 짧습니다, %1$d 개의 문자가 최소 필요합니다.',
		2	=> 'The field “%2$s” is too short, a minimum of %1$d characters is required.',
	),
	'FIELD_TOO_LONG'					=> array(
		1	=> 'The field “%2$s” is too long, a maximum of %1$d character is allowed.',
		2	=> 'The field “%2$s” is too long, a maximum of %1$d characters is allowed.',
	),
	'FIELD_TOO_SMALL'					=> 'The value of “%2$s” is too small, a minimum value of %1$d is required.',
	'FIELD_TOO_LARGE'					=> 'The value of “%2$s” is too large, a maximum value of %1$d is allowed.',
	'FIELD_INVALID_CHARS_INVALID'		=> 'The field “%s” has invalid characters.',
	'FIELD_INVALID_CHARS_NUMBERS_ONLY'	=> 'The field “%s” has invalid characters, only numbers are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_DOTS'	=> 'The field “%s” has invalid characters, only alphanumeric or . characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_ONLY'	=> 'The field “%s” has invalid characters, only alphanumeric characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_PUNCTUATION'	=> 'The field “%s” has invalid characters, only alphanumeric or _,-. characters are allowed and the first character must be alphabetic.',
	'FIELD_INVALID_CHARS_ALPHA_SPACERS'	=> 'The field “%s” has invalid characters, only alphanumeric, space or -+_[] characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_UNDERSCORE'	=> 'The field “%s” has invalid characters, only alphanumeric or _ characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_DOTS'	=> 'The field “%s” has invalid characters, only letter, number or . characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_ONLY'	=> 'The field “%s” has invalid characters, only letter and number characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_PUNCTUATION'	=> 'The field “%s” has invalid characters, only letter, number or _,-. characters are allowed and the first character must be alphabetic.',
	'FIELD_INVALID_CHARS_LETTER_NUM_SPACERS'		=> 'The field “%s” has invalid characters, only letter, number, space or -+_[] characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_UNDERSCORE'		=> 'The field “%s” has invalid characters, only letter, number or _ characters are allowed.',
	'FIELD_INVALID_DATE'				=> 'The field “%s” has an invalid date.',
	'FIELD_INVALID_URL'					=> 'The field “%s” has an invalid url.',
	'FIELD_INVALID_VALUE'				=> 'The field “%s” has an invalid value.',

	'FOE_MESSAGE'				=> 'Message from foe',
	'FOES_EXPLAIN'				=> 'Foes are users which will be ignored by default. Posts by these users will not be fully visible. Personal messages from foes are still permitted. Please note that you cannot ignore moderators or administrators.',
	'FOES_UPDATED'				=> 'Your foes list has been updated successfully.',
	'FOLDER_ADDED'				=> 'Folder successfully added.',
	'FOLDER_MESSAGE_STATUS'		=> array(
		1	=> '%2$d out of %1$s stored',
		2	=> '%2$d out of %1$s stored',
	),
	'FOLDER_NAME_EMPTY'			=> 'You must enter a name for this folder.',
	'FOLDER_NAME_EXIST'			=> 'Folder <strong>%s</strong> already exists.',
	'FOLDER_OPTIONS'			=> 'Folder options',
	'FOLDER_RENAMED'			=> 'Folder successfully renamed.',
	'FOLDER_REMOVED'			=> 'Folder successfully removed.',
	'FOLDER_STATUS_MSG'			=> array(
		1	=> 'Folder is %3$d%% full (%2$d out of %1$s stored)',
		2	=> 'Folder is %3$d%% full (%2$d out of %1$s stored)',
	),
	'FORWARD_PM'				=> 'Forward PM',
	'FORCE_PASSWORD_EXPLAIN'	=> 'Before you may continue browsing the board you are required to change your password.',
	'FRIEND_MESSAGE'			=> 'Message from friend',
	'FRIENDS'					=> 'Friends',
	'FRIENDS_EXPLAIN'			=> 'Friends enable you quick access to members you communicate with frequently. If the template has relevant support any posts made by a friend may be highlighted.',
	'FRIENDS_OFFLINE'			=> 'Offline',
	'FRIENDS_ONLINE'			=> 'Online',
	'FRIENDS_UPDATED'			=> 'Your friends list has been updated successfully.',
	'FULL_FOLDER_OPTION_CHANGED'=> 'The action to take when a folder is full has been changed successfully.',
	'FWD_ORIGINAL_MESSAGE'		=> '-------- Original Message --------',
	'FWD_SUBJECT'				=> 'Subject: %s',
	'FWD_DATE'					=> 'Date: %s',
	'FWD_FROM'					=> 'From: %s',
	'FWD_TO'					=> 'To: %s',

	'GLOBAL_ANNOUNCEMENT'		=> 'Global announcement',

	'GRAVATAR_AVATAR_EMAIL'			=> 'Gravatar email',
	'GRAVATAR_AVATAR_EMAIL_EXPLAIN'	=> 'Enter the email address you used for registering your account on <a href="http://www.gravatar.com/">Gravatar</a>.',
	'GRAVATAR_AVATAR_SIZE'			=> 'Avatar dimensions',
	'GRAVATAR_AVATAR_SIZE_EXPLAIN'	=> 'Specify the width and height of the avatar, leave blank to attempt automatic verification.',

	'HIDE_ONLINE'				=> 'Hide my online status',
	'HIDE_ONLINE_EXPLAIN'		=> 'Changing this setting won’t become effective until your next visit to the board.',
	'HOLD_NEW_MESSAGES'			=> 'Do not accept new messages (New messages will be held back until enough space is available)',
	'HOLD_NEW_MESSAGES_SHORT'	=> 'New messages will be held back',

	'IF_FOLDER_FULL'			=> 'If folder is full',
	'IMPORTANT_NEWS'			=> 'Important announcements',
	'INVALID_USER_BIRTHDAY'			=> 'The entered birthday is not a valid date.',
	'INVALID_CHARS_USERNAME'	=> 'The username contains forbidden characters.',
	'INVALID_CHARS_NEW_PASSWORD'=> 'The password does not contain the required characters.',
	'ITEMS_REQUIRED'			=> 'The items marked with * are required profile fields and need to be filled out.',

	'JOIN_SELECTED'				=> 'Join selected',

	'LANGUAGE'					=> 'Language',
	'LINK_REMOTE_AVATAR'		=> 'Link off-site',
	'LINK_REMOTE_AVATAR_EXPLAIN'=> 'Enter the URL of the location containing the avatar image you wish to link to.',
	'LINK_REMOTE_SIZE'			=> 'Avatar dimensions',
	'LINK_REMOTE_SIZE_EXPLAIN'	=> 'Specify the width and height of the avatar, leave blank to attempt automatic verification.',
	'LOGIN_EXPLAIN_UCP'			=> 'Please login in order to access the User Control Panel.',
	'LOGIN_LINK'					=> 'Link or register your account on an external service with your board account',
	'LOGIN_LINK_EXPLAIN'			=> 'You have attempted to login with an external service that is not yet connected to an account on this board. You must now either link this account to an existing account or create a new account.',
	'LOGIN_LINK_MISSING_DATA'		=> 'Data that is necessary to link your account with an external service is not available. Please restart the login process.',
	'LOGIN_LINK_NO_DATA_PROVIDED'	=> 'No data has been provided to this page to link an external account to a forum account. Please contact the board administrator if you continue to experience problems.',
	'LOGIN_KEY'					=> 'Login Key',
	'LOGIN_TIME'				=> 'Login Time',
	'LOGIN_REDIRECT'			=> 'You have been successfully logged in.',
	'LOGOUT_FAILED'				=> 'You were not logged out, as the request did not match your session. Please contact the board administrator if you continue to experience problems.',
	'LOGOUT_REDIRECT'			=> 'You have been successfully logged out.',

	'MARK_IMPORTANT'				=> 'Mark/Unmark as important',
	'MARKED_MESSAGE'				=> 'Marked message',
	'MAX_FOLDER_REACHED'			=> 'Maximum number of allowed user defined folders reached.',
	'MESSAGE_BY_AUTHOR'				=> 'by',
	'MESSAGE_COLOURS'				=> 'Message colours',
	'MESSAGE_DELETED'				=> 'Message successfully deleted.',
	'MESSAGE_EDITED'				=> 'Message successfully edited.',
	'MESSAGE_HISTORY'				=> 'Message history',
	'MESSAGE_REMOVED_FROM_OUTBOX'	=> 'This message was deleted by its author.',
	'MESSAGE_SENT_ON'				=> 'on',
	'MESSAGE_STORED'				=> 'This message has been sent successfully.',
	'MESSAGE_TO'					=> 'To',
	'MESSAGES_DELETED'				=> 'Messages successfully deleted',
	'MOVE_DELETED_MESSAGES_TO'		=> 'Move messages from removed folder to',
	'MOVE_DOWN'						=> 'Move down',
	'MOVE_MARKED_TO_FOLDER'			=> 'Move marked to %s',
	'MOVE_PM_ERROR'					=> array(
		1	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s was moved.',
		2	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s were moved.',
	),
	'MOVE_TO_FOLDER'				=> 'Move to folder',
	'MOVE_UP'						=> 'Move up',

	'NEW_FOLDER_NAME'				=> 'New folder name',
	'NEW_PASSWORD'					=> 'New password',
	'NEW_PASSWORD_CONFIRM_EMPTY'	=> 'You did not enter a confirm password.',
	'NEW_PASSWORD_ERROR'			=> 'The passwords you entered do not match.',

	'NOTIFICATIONS_MARK_ALL_READ'						=> 'Mark all notifications read',
	'NOTIFICATIONS_MARK_ALL_READ_CONFIRM'				=> 'Are you sure you want to mark all notifications read?',
	'NOTIFICATIONS_MARK_ALL_READ_SUCCESS'				=> 'All notifications have been marked read.',
	'NOTIFICATION_GROUP_MISCELLANEOUS'					=> 'Miscellaneous Notifications',
	'NOTIFICATION_GROUP_MODERATION'						=> 'Moderation Notifications',
	'NOTIFICATION_GROUP_ADMINISTRATION'					=> 'Administration Notifications',
	'NOTIFICATION_GROUP_POSTING'						=> 'Posting Notifications',
	'NOTIFICATION_METHOD_EMAIL'							=> 'Email',
	'NOTIFICATION_METHOD_JABBER'						=> 'Jabber',
	'NOTIFICATION_TYPE'									=> 'Notification type',
	'NOTIFICATION_TYPE_BOOKMARK'						=> 'Someone replies to a topic you have bookmarked',
	'NOTIFICATION_TYPE_GROUP_REQUEST'					=> 'Someone requests to join a group you lead',
	'NOTIFICATION_TYPE_IN_MODERATION_QUEUE'				=> 'A post or topic needs approval',
	'NOTIFICATION_TYPE_MODERATION_QUEUE'				=> 'Your topics/posts are approved or disapproved by a moderator',
	'NOTIFICATION_TYPE_PM'								=> 'Someone sends you a private message',
	'NOTIFICATION_TYPE_POST'							=> 'Someone replies to a topic to which you are subscribed',
	'NOTIFICATION_TYPE_QUOTE'							=> 'Someone quotes you in a post',
	'NOTIFICATION_TYPE_REPORT'							=> 'Someone reports a post',
	'NOTIFICATION_TYPE_TOPIC'							=> 'Someone creates a topic in a forum to which you are subscribed',
	'NOTIFICATION_TYPE_ADMIN_ACTIVATE_USER'				=> 'Newly registered user requiring activation',

	'NOTIFY_METHOD'					=> 'Notification method',
	'NOTIFY_METHOD_BOTH'			=> 'Both',
	'NOTIFY_METHOD_EMAIL'			=> 'Email only',
	'NOTIFY_METHOD_EXPLAIN'			=> 'Method for sending messages sent via this board.',
	'NOTIFY_METHOD_IM'				=> 'Jabber only',
	'NOTIFY_ON_PM'					=> 'Notify me on new private messages',
	'NOT_ADDED_FRIENDS_ANONYMOUS'	=> 'You cannot add the anonymous user to your friends list.',
	'NOT_ADDED_FRIENDS_BOTS'		=> 'You cannot add bots to your friends list.',
	'NOT_ADDED_FRIENDS_FOES'		=> 'You cannot add users to your friends list who are on your foes list.',
	'NOT_ADDED_FRIENDS_SELF'		=> 'You cannot add yourself to the friends list.',
	'NOT_ADDED_FOES_MOD_ADMIN'		=> 'You cannot add administrators and moderators to your foes list.',
	'NOT_ADDED_FOES_ANONYMOUS'		=> 'You cannot add the anonymous user to your foes list.',
	'NOT_ADDED_FOES_BOTS'			=> 'You cannot add bots to your foes list.',
	'NOT_ADDED_FOES_FRIENDS'		=> 'You cannot add users to your foes list who are on your friends list.',
	'NOT_ADDED_FOES_SELF'			=> 'You cannot add yourself to the foes list.',
	'NOT_AGREE'						=> 'I do not agree to these terms',
	'NOT_ENOUGH_SPACE_FOLDER'		=> 'The destination folder “%s” seems to be full. The requested action has not been taken.',
	'NOT_MOVED_MESSAGES'			=> array(
		1	=> 'You have %d private message currently on hold because of full folder.',
		2	=> 'You have %d private messages currently on hold because of full folder.',
	),
	'NO_ACTION_MODE'				=> 'No message action specified.',
	'NO_AUTHOR'						=> 'No author defined for this message',
	'NO_AVATAR'						=> 'No avatar selected',
	'NO_AVATAR_CATEGORY'			=> 'None',

	'NO_AUTH_DELETE_MESSAGE'		=> 'You are not authorised to delete private messages.',
	'NO_AUTH_EDIT_MESSAGE'			=> 'You are not authorised to edit private messages.',
	'NO_AUTH_FORWARD_MESSAGE'		=> 'You are not authorised to forward private messages.',
	'NO_AUTH_GROUP_MESSAGE'			=> 'You are not authorised to send private messages to groups.',
	'NO_AUTH_PASSWORD_REMINDER'		=> 'You are not authorised to request a new password.',
	'NO_AUTH_PROFILEINFO'			=> 'You are not authorised to change your profile information.',
	'NO_AUTH_READ_HOLD_MESSAGE'		=> 'You are not authorised to read private messages that are on hold.',
	'NO_AUTH_READ_MESSAGE'			=> 'You are not authorised to read private messages.',
	'NO_AUTH_READ_REMOVED_MESSAGE'	=> 'You are not able to read this message because it was removed by the author.',
	'NO_AUTH_SEND_MESSAGE'			=> 'You are not authorised to send private messages.',
	'NO_AUTH_SIGNATURE'				=> 'You are not authorised to define a signature.',

	'NO_BCC_RECIPIENT'			=> 'None',
	'NO_BOOKMARKS'				=> 'You have no bookmarks.',
	'NO_BOOKMARKS_SELECTED'		=> 'You have selected no bookmarks.',
	'NO_EDIT_READ_MESSAGE'		=> 'Private message cannot be edited because it has already been read.',
	'NO_EMAIL_USER'				=> 'The email/username information submitted could not be found.',
	'NO_FOES'					=> 'No foes currently defined',
	'NO_FRIENDS'				=> 'No friends currently defined',
	'NO_FRIENDS_OFFLINE'		=> 'No friends offline',
	'NO_FRIENDS_ONLINE'			=> 'No friends online',
	'NO_GROUP_SELECTED'			=> 'No group specified.',
	'NO_IMPORTANT_NEWS'			=> 'No important announcements present.',
	'NO_MESSAGE'				=> 'Private message could not be found.',
	'NO_NEW_FOLDER_NAME'		=> 'You have to specify a new folder name.',
	'NO_NEWER_PM'				=> 'No newer messages.',
	'NO_OLDER_PM'				=> 'No older messages.',
	'NO_PASSWORD_SUPPLIED'		=> 'You cannot login without a password.',
	'NO_RECIPIENT'				=> 'No recipient defined.',
	'NO_RULES_DEFINED'			=> 'No rules defined.',
	'NO_SAVED_DRAFTS'			=> 'No drafts saved.',
	'NO_TO_RECIPIENT'			=> 'None',
	'NO_WATCHED_FORUMS'			=> 'You are not subscribed to any forums.',
	'NO_WATCHED_SELECTED'		=> 'You have not selected any subscribed topics or forums.',
	'NO_WATCHED_TOPICS'			=> 'You are not subscribed to any topics.',

	'PASS_TYPE_ALPHA_EXPLAIN'	=> 'Password must be between %1$s and %2$s long, must contain letters in mixed case and must contain numbers.',
	'PASS_TYPE_ANY_EXPLAIN'		=> 'Must be between %1$s and %2$s.',
	'PASS_TYPE_CASE_EXPLAIN'	=> 'Password must be between %1$s and %2$s long and must contain letters in mixed case.',
	'PASS_TYPE_SYMBOL_EXPLAIN'	=> 'Password must be between %1$s and %2$s long, must contain letters in mixed case, must contain numbers and must contain symbols.',
	'PASSWORD'					=> '비밀번호',
	'PASSWORD_ACTIVATED'		=> 'Your new password has been activated.',
	'PASSWORD_UPDATED'			=> 'A new password was sent to your registered email address.',
	'PERMISSIONS_RESTORED'		=> 'Successfully restored original permissions.',
	'PERMISSIONS_TRANSFERRED'	=> 'Successfully transferred permissions from <strong>%s</strong>, you are now able to browse the board with this user’s permissions.<br />Please note that admin permissions were not transferred. You are able to revert to your permission set at any time.',
	'PM_DISABLED'				=> 'Private messaging has been disabled on this board.',
	'PM_FROM'					=> 'From',
	'PM_FROM_REMOVED_AUTHOR'	=> 'This message was sent by a user no longer registered.',
	'PM_ICON'					=> 'PM icon',
	'PM_INBOX'					=> 'Inbox',
	'PM_MARK_ALL_READ'			=> 'Mark all messages read',
	'PM_MARK_ALL_READ_SUCCESS'	=> 'All private messages in this folder have been marked read',
	'PM_NO_USERS'				=> 'The requested users to be added do not exist.',
	'PM_OUTBOX'					=> 'Outbox',
	'PM_SENTBOX'				=> 'Sent messages',
	'PM_SUBJECT'				=> 'Message subject',
	'PM_TO'						=> 'Send to',
	'PM_TOOLS'					=> 'Message tools',
	'PM_USERS_REMOVED_NO_PERMISSION'	=> 'Some users couldn’t be added as they do not have permission to read private messages.',
	'PM_USERS_REMOVED_NO_PM'	=> 'Some users couldn’t be added as they have disabled private message receipt.',
	'POST_EDIT_PM'				=> 'Edit message',
	'POST_FORWARD_PM'			=> 'Forward message',
	'POST_NEW_PM'				=> 'Compose message',
	'POST_PM_LOCKED'			=> 'Private messaging is locked.',
	'POST_PM_POST'				=> 'Quote post',
	'POST_QUOTE_PM'				=> 'Quote message',
	'POST_REPLY_PM'				=> 'Reply to message',
	'PRINT_PM'					=> 'Print view',
	'PREFERENCES_UPDATED'		=> 'Your preferences have been updated.',
	'PROFILE_INFO_NOTICE'		=> 'Please note that this information may be viewable to other members. Be careful when including any personal details. Any fields marked with a * must be completed.',
	'PROFILE_UPDATED'			=> 'Your profile has been updated.',
	'PROFILE_AUTOLOGIN_KEYS'	=> 'The "Remember Me" login keys automatically log you in when you visit the board. If you logout, the remember me login key is deleted only on the computer you are using to logout. Here you can see remember login keys created on other computers you used to access this site.',
	'PROFILE_NO_AUTOLOGIN_KEYS'	=> 'There are no saved "Remember Me" login keys.',

	'RECIPIENT'							=> 'Recipient',
	'RECIPIENTS'						=> 'Recipients',
	'REGISTRATION'						=> 'Registration',
	'RELEASE_MESSAGES'					=> '%sRelease all on-hold messages%s… they will be re-sorted into the appropriate folder if enough space is made available.',
	'REMOVE_ADDRESS'					=> 'Remove address',
	'REMOVE_SELECTED_BOOKMARKS'			=> 'Remove selected bookmarks',
	'REMOVE_SELECTED_BOOKMARKS_CONFIRM'	=> 'Are you sure you want to delete all selected bookmarks?',
	'REMOVE_BOOKMARK_MARKED'			=> 'Remove marked bookmarks',
	'REMOVE_FOLDER'						=> 'Remove folder',
	'REMOVE_FOLDER_CONFIRM'				=> 'Are you sure you want to remove this folder?',
	'RENAME'							=> 'Rename',
	'RENAME_FOLDER'						=> 'Rename folder',
	'REPLIED_MESSAGE'					=> 'Replied to message',
	'REPLY_TO_ALL'						=> 'Reply to sender and all recipients.',
	'REPORT_PM'							=> 'Report private message',
	'RESIGN_SELECTED'					=> 'Resign selected',
	'RETURN_FOLDER'						=> '%1$sReturn to previous folder%2$s',
	'RETURN_UCP'						=> '%sReturn to the User Control Panel%s',
	'RULE_ADDED'						=> 'Rule successfully added.',
	'RULE_ALREADY_DEFINED'				=> 'This rule was defined previously.',
	'RULE_DELETED'						=> 'Rule successfully removed.',
	'RULE_LIMIT_REACHED'				=> 'You cannot add more PM rules. You have reached the maximum number of rules.',
	'RULE_NOT_DEFINED'					=> 'Rule not correctly specified.',
	'RULE_REMOVED_MESSAGES'				=> array(
		1	=> '%d private message was removed due to private message filters.',
		2	=> '%d private messages were removed due to private message filters.',
	),

	'SAME_PASSWORD_ERROR'		=> 'The new password you entered is the same as your current password.',
	'SEARCH_YOUR_POSTS'			=> 'Show your posts',
	'SEND_PASSWORD'				=> 'Send password',
	'SENT_AT'					=> 'Sent',			// Used before dates in private messages
	'SHOW_EMAIL'				=> 'Users can contact me by email',
	'SIGNATURE_EXPLAIN'			=> 'This is a block of text that can be added to posts you make. There is a %d character limit.',
	'SIGNATURE_PREVIEW'			=> 'Your signature will appear like this in posts',
	'SIGNATURE_TOO_LONG'		=> 'Your signature is too long.',
	'SELECT_CURRENT_TIME'		=> 'Select current time',
	'SELECT_TIMEZONE'			=> 'Select timezone',
	'SORT'						=> 'Sort',
	'SORT_COMMENT'				=> 'File comment',
	'SORT_DOWNLOADS'			=> 'Downloads',
	'SORT_EXTENSION'			=> 'Extension',
	'SORT_FILENAME'				=> 'Filename',
	'SORT_POST_TIME'			=> 'Post time',
	'SORT_SIZE'					=> 'File size',

	'TIMEZONE'					=> 'Timezone',
	'TIMEZONE_DATE_SUGGESTION'	=> 'Suggestion: %s',
	'TIMEZONE_INVALID'			=> 'The timezone you selected is invalid.',
	'TO'						=> 'Recipient',
	'TO_MASS'					=> 'Recipients',
	'TO_ADD'					=> 'Add recipient',
	'TO_ADD_MASS'				=> 'Add recipients',
	'TO_ADD_GROUPS'				=> 'Add groups',
	'TOO_MANY_RECIPIENTS'		=> 'You tried to send a private message to too many recipients.',
	'TOO_MANY_REGISTERS'		=> 'You have exceeded the maximum number of registration attempts for this session. Please try again later.',

	'UCP'						=> 'User Control Panel',
	'UCP_ACTIVATE'				=> 'Activate account',
	'UCP_ADMIN_ACTIVATE'		=> 'Please note that you will need to enter a valid email address before your account is activated. The administrator will review your account and if approved you will receive an email at the address you specified.',
	'UCP_ATTACHMENTS'			=> 'Attachments',
	'UCP_AUTH_LINK'				=> 'External accounts',
	'UCP_AUTH_LINK_ASK'			=> 'You currently have no account associated with this external service. Click the button below to link your board account to an account with this external service.',
	'UCP_AUTH_LINK_ID'			=> 'Unique identifier',
	'UCP_AUTH_LINK_LINK'		=> 'Link',
	'UCP_AUTH_LINK_MANAGE'		=> 'Manage external account associations',
	'UCP_AUTH_LINK_NOT_SUPPORTED'	=> 'Linking board accounts to external services is not supported by this board’s current authentication method.',
	'UCP_AUTH_LINK_TITLE'		=> 'Manage your external account associations',
	'UCP_AUTH_LINK_UNLINK'		=> 'Unlink',
	'UCP_COPPA_BEFORE'			=> 'Before %s',
	'UCP_COPPA_ON_AFTER'		=> 'On or after %s',
	'UCP_EMAIL_ACTIVATE'		=> 'Please note that you will need to enter a valid email address before your account is activated. You will receive an email at the address you provide that contains an account activation link.',
	'UCP_JABBER'				=> 'Jabber address',
	'UCP_LOGIN_LINK'			=> 'Set up an external account association',

	'UCP_MAIN'					=> 'Overview',
	'UCP_MAIN_ATTACHMENTS'		=> 'Manage attachments',
	'UCP_MAIN_BOOKMARKS'		=> 'Manage bookmarks',
	'UCP_MAIN_DRAFTS'			=> 'Manage drafts',
	'UCP_MAIN_FRONT'			=> 'Front page',
	'UCP_MAIN_SUBSCRIBED'		=> 'Manage subscriptions',

	'UCP_NO_ATTACHMENTS'		=> 'You have posted no files.',

	'UCP_NOTIFICATION_LIST'				=> 'Manage notifications',
	'UCP_NOTIFICATION_LIST_EXPLAIN'		=> 'Here you may view all past notifications.',
	'UCP_NOTIFICATION_OPTIONS'			=> 'Edit notification options',
	'UCP_NOTIFICATION_OPTIONS_EXPLAIN'	=> 'Here you can set your preferred notification methods for the board.',

	'UCP_PREFS'					=> 'Board preferences',
	'UCP_PREFS_PERSONAL'		=> 'Edit global settings',
	'UCP_PREFS_POST'			=> 'Edit posting defaults',
	'UCP_PREFS_VIEW'			=> 'Edit display options',

	'UCP_PM'					=> 'Private messages',
	'UCP_PM_COMPOSE'			=> 'Compose message',
	'UCP_PM_DRAFTS'				=> 'Manage PM drafts',
	'UCP_PM_OPTIONS'			=> 'Rules, folders &amp; settings',
	'UCP_PM_UNREAD'				=> 'Unread messages',
	'UCP_PM_VIEW'				=> 'View messages',

	'UCP_PROFILE'				=> 'Profile',
	'UCP_PROFILE_AVATAR'		=> 'Edit avatar',
	'UCP_PROFILE_PROFILE_INFO'	=> 'Edit profile',
	'UCP_PROFILE_REG_DETAILS'	=> 'Edit account settings',
	'UCP_PROFILE_SIGNATURE'		=> 'Edit signature',
	'UCP_PROFILE_AUTOLOGIN_KEYS'=> 'Manage “Remember Me” login keys',

	'UCP_USERGROUPS'			=> 'Usergroups',
	'UCP_USERGROUPS_MEMBER'		=> 'Edit memberships',
	'UCP_USERGROUPS_MANAGE'		=> 'Manage groups',

	'UCP_PASSWORD_RESET_DISABLED'	=> 'The password reset functionality has been disabled. If you need help accessing your account, please contact the %sBoard Administrator%s',
	'UCP_REGISTER_DISABLE'			=> 'Creating a new account is currently not possible.',
	'UCP_REMIND'					=> 'Send password',
	'UCP_RESEND'					=> 'Send activation email',
	'UCP_WELCOME'					=> 'Welcome to the User Control Panel. From here you can monitor, view and update your profile, preferences, subscribed forums and topics. You can also send messages to other users (if permitted). Please ensure you read any announcements before continuing.',
	'UCP_ZEBRA'						=> 'Friends &amp; Foes',
	'UCP_ZEBRA_FOES'				=> 'Manage foes',
	'UCP_ZEBRA_FRIENDS'				=> 'Manage friends',
	'UNDISCLOSED_RECIPIENT'			=> 'Undisclosed Recipient',
	'UNKNOWN_FOLDER'				=> 'Unknown folder',
	'UNWATCH_MARKED'				=> 'Unwatch marked',
	'UPLOAD_AVATAR_FILE'			=> 'Upload from your machine',
	'UPLOAD_AVATAR_URL'				=> 'Upload from a URL',
	'UPLOAD_AVATAR_URL_EXPLAIN'		=> 'Enter the URL of the location containing the image. The image will be copied to this site.',
	'USERNAME_ALPHA_ONLY_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only alphanumeric characters.',
	'USERNAME_ALPHA_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use alphanumeric, space or -+_[] characters.',
	'USERNAME_ASCII_EXPLAIN'		=> 'Username must be between %1$s and %2$s long and use only ASCII characters, so no special symbols.',
	'USERNAME_LETTER_NUM_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only letter or number characters.',
	'USERNAME_LETTER_NUM_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use letter, number, space or -+_[] characters.',
	'USERNAME_CHARS_ANY_EXPLAIN'	=> 'Length must be between %1$s and %2$s.',
	'USERNAME_TAKEN_USERNAME'		=> 'The username you entered is already in use, please select an alternative.',
	'USERNAME_DISALLOWED_USERNAME'	=> 'The username you entered has been disallowed or contains a disallowed word. Please choose a different name.',
	'USER_NOT_FOUND_OR_INACTIVE'	=> 'The usernames you specified could either not be found or are not activated users.',

	'VIEW_AVATARS'				=> 'Display avatars',
	'VIEW_EDIT'					=> 'View/Edit',
	'VIEW_FLASH'				=> 'Display Flash animations',
	'VIEW_IMAGES'				=> 'Display images within posts',
	'VIEW_NEXT_HISTORY'			=> 'Next PM in history',
	'VIEW_NEXT_PM'				=> 'Next PM',
	'VIEW_PM'					=> 'View message',
	'VIEW_PM_INFO'				=> 'Message details',
	'VIEW_PM_MESSAGES'			=> array(
		1	=> '%d message',
		2	=> '%d messages',
	),
	'VIEW_PREVIOUS_HISTORY'		=> 'Previous PM in history',
	'VIEW_PREVIOUS_PM'			=> 'Previous PM',
	'VIEW_PROFILE'				=> 'View profile',
	'VIEW_SIGS'					=> 'Display signatures',
	'VIEW_SMILIES'				=> 'Display smilies as images',
	'VIEW_TOPICS_DAYS'			=> 'Display topics from previous days',
	'VIEW_TOPICS_DIR'			=> 'Display topic order direction',
	'VIEW_TOPICS_KEY'			=> 'Display topics ordering by',
	'VIEW_POSTS_DAYS'			=> 'Display posts from previous days',
	'VIEW_POSTS_DIR'			=> 'Display post order direction',
	'VIEW_POSTS_KEY'			=> 'Display posts ordering by',

	'WATCHED_EXPLAIN'			=> 'Below is a list of forums and topics you are subscribed to. You will be notified of new posts in either. To unsubscribe mark the forum or topic and then press the <em>Unwatch marked</em> button.',
	'WATCHED_FORUMS'			=> 'Watched forums',
	'WATCHED_TOPICS'			=> 'Watched topics',
	'WRONG_ACTIVATION'			=> 'The activation key you supplied does not match any in the database.',

	'YOUR_DETAILS'				=> 'Your activity',
	'YOUR_FOES'					=> 'Your foes',
	'YOUR_FOES_EXPLAIN'			=> 'To remove usernames select them and click submit.',
	'YOUR_FRIENDS'				=> 'Your friends',
	'YOUR_FRIENDS_EXPLAIN'		=> 'To remove usernames select them and click submit.',
	'YOUR_WARNINGS'				=> 'Your warning level',

	'PM_ACTION' => array(
		'PLACE_INTO_FOLDER'	=> 'Place into folder',
		'MARK_AS_READ'		=> 'Mark as read',
		'MARK_AS_IMPORTANT'	=> 'Mark message',
		'DELETE_MESSAGE'	=> '삭제 message',
	),
	'PM_CHECK' => array(
		'SUBJECT'	=> 'Subject',
		'SENDER'	=> 'Sender',
		'MESSAGE'	=> 'Message',
		'STATUS'	=> 'Message status',
		'TO'		=> 'Sent To',
	),
	'PM_RULE' => array(
		'IS_LIKE'		=> 'is like',
		'IS_NOT_LIKE'	=> 'is not like',
		'IS'			=> 'is',
		'IS_NOT'		=> 'is not',
		'BEGINS_WITH'	=> 'begins with',
		'ENDS_WITH'		=> 'ends with',
		'IS_FRIEND'		=> 'is friend',
		'IS_FOE'		=> 'is foe',
		'IS_USER'		=> 'is user',
		'IS_GROUP'		=> 'is in usergroup',
		'ANSWERED'		=> 'answered',
		'FORWARDED'		=> 'forwarded',
		'TO_GROUP'		=> 'to my default usergroup',
		'TO_ME'			=> 'to me',
	),

	'GROUPS_EXPLAIN'	=> 'Usergroups enable board admins to better administer users. By default you will be placed in a specific group, this is your default group. This group defines how you may appear to other users, for example your username colouration, avatar, rank, etc. Depending on whether the administrator allows it you may be allowed to change your default group. You may also be placed in or allowed to join other groups. Some groups may give you additional permissions to view content or increase your capabilities in other areas.',
	'GROUP_LEADER'		=> 'Leaderships',
	'GROUP_MEMBER'		=> 'Memberships',
	'GROUP_PENDING'		=> 'Pending memberships',
	'GROUP_NONMEMBER'	=> 'Non-memberships',
	'GROUP_DETAILS'		=> 'Group details',

	'NO_LEADER'		=> 'No group leaderships',
	'NO_MEMBER'		=> 'No group memberships',
	'NO_PENDING'	=> 'No pending memberships',
	'NO_NONMEMBER'	=> 'No non-member groups',
));
